resources:
- name: smb-broker-image
  type: s3
  source:
    region_name: us-east-2
    bucket: smb-broker-k8s-images
    versioned_file: smb-broker.tgz
    initial_version: "0"
    access_key_id: {{smb-broker-k8s-images-bucket-access_aws_ID}}
    secret_access_key: {{smb-broker-k8s-images-bucket-access_aws_secret}}

- name: smb-volume-k8s-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/smb-volume-k8s-release
    branch: master
    private_key: {{smb-broker-k8s-github-deploy-key}}

- name: smb-broker-docker-image
  type: docker-image
  source:
    repository: cfpersi/smb-broker
    username: ((dockerhub_username))
    password: ((dockerhub_password))

- name: smb-csi-driver-docker-image
  type: docker-image
  source:
    repository: cfpersi/smb-csi-driver
    username: ((dockerhub_username))
    password: ((dockerhub_password))

- name: smb-release-version
  type: semver
  source:
    access_key_id: {{smb-release-k8s-uploader_aws_ID}}
    bucket: smb-release-versions-k8s
    initial_version: 0.0.0
    key: current-version
    region_name: us-east-1
    secret_access_key: {{smb-release-k8s-uploader_aws_secret}}

jobs:
- name: smb-broker-unit-tests
  serial: true
  plan:
    - get: smb-volume-k8s-release
      trigger: true
    - task: unit-tests
      attempts: 3
      file: smb-volume-k8s-release/smb-broker/ci/unit-tests.yml
      privileged: true
    - put: smb-broker-image
      params:
        file: built-images/smb-broker.tgz

- name: smb-csi-driver-units
  plan:
    - get: smb-volume-k8s-release
      trigger: true
    - task: run-test
      attempts: 3
      privileged: true
      file: smb-volume-k8s-release/smb-csi-driver/ci/unit-tests.yml

- name: integration-tests
  plan:
    - get: smb-volume-k8s-release
      trigger: true
    - task: run-test
      attempts: 3
      privileged: true
      file: smb-volume-k8s-release/ci/integration-tests.yml

- name: smb-csi-driver-e2e-tests
  plan:
    - get: smb-volume-k8s-release
      trigger: true
    - task: e2e-tests
      attempts: 3
      privileged: true
      file: smb-volume-k8s-release/smb-csi-driver/ci/e2e-tests.yml

- name: create-github-tag
  serial: true
  plan:
    - get: smb-volume-k8s-release
      trigger: true
      passed:
        - smb-broker-unit-tests
        - smb-csi-driver-units
        - smb-csi-driver-e2e-tests
        - integration-tests
    - get: smb-release-version
      params:
        bump: minor
    - get: smb-broker-image
      passed:
      - smb-broker-unit-tests
    - put: smb-volume-k8s-release
      params:
        repository: smb-volume-k8s-release
        tag: smb-release-version/version
        only_tag: true
    - put: smb-release-version
      params:
        bump: minor

- name: build-smb-broker-docker-image
  plan:
    - get: smb-volume-k8s-release
      passed:
      - create-github-tag
      trigger: true
    - get: smb-release-version
      passed:
      - create-github-tag
    - get: smb-broker-image
      passed:
        - create-github-tag
    - put: smb-broker-docker-image
      params:
        load_repository: localhost:5000/cfpersi/smb-broker
        load_file: smb-broker-image/smb-broker.tgz
        load_tag: local-test
        tag_file: smb-release-version/version
        tag_as_latest: true

- name: build-smb-csi-driver-docker-image
  plan:
    - get: smb-volume-k8s-release
      passed:
        - create-github-tag
      trigger: true
    - get: smb-release-version
      passed:
        - create-github-tag
    - put: smb-csi-driver-docker-image
      params:
        tag_file: smb-release-version/version
        tag_as_latest: true
        build: smb-volume-k8s-release/smb-csi-driver