groups:
- name: all-jobs
  jobs:
  - smb-broker-unit-tests
  - smb-csi-driver-integration-tests
  - build-smb-broker-docker-image
  - pats

resources:
- name: smb-volume-k8s-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/smb-volume-k8s-release
    branch: master
    private_key: {{smb-broker-k8s-github-deploy-key}}

- name: smb-broker-docker-image
  type: docker-image
  source:
    repository: cfpersi/smb-broker
    username: ((dockerhub_username))
    password: ((dockerhub_password))


- name: smb-broker-version
  type: semver
  source:
    access_key_id: {{smb-broker-k8s-uploader_aws_ID}}
    bucket: smb-broker-versions-k8s
    initial_version: 0.0.0
    key: current-version
    region_name: us-east-1
    secret_access_key: {{smb-broker-k8s-uploader_aws_secret}}

- name: persi-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git

- name: cf-volume-services-acceptance-tests
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-volume-services-acceptance-tests.git
    
jobs:
- name: smb-broker-unit-tests
  serial: true
  plan:
    - get: smb-volume-k8s-release
      trigger: true
    - task: unit-tests
      file: smb-volume-k8s-release/smb-broker/ci/unit-tests.yml
      privileged: true
    - get: smb-broker-version
      params:
        bump: minor
    - put: smb-volume-k8s-release
      params:
        repository: smb-volume-k8s-release
        tag: smb-broker-version/version
        only_tag: true
    - put: smb-broker-version
      params:
        bump: minor

- name: smb-csi-driver-integration-tests
  plan:
    - get: smb-volume-k8s-release
      trigger: true
    - task: integration-tests
      privileged: true
      file: smb-volume-k8s-release/smb-csi-driver/ci/integration-tests.yml

- name: build-smb-broker-docker-image
  plan:
    - get: smb-volume-k8s-release
      passed:
      - smb-broker-unit-tests
      trigger: true
    - get: smb-broker-version
      passed:
      - smb-broker-unit-tests
    - put: smb-broker-docker-image
      params:
        tag_file: smb-broker-version/version
        tag_as_latest: true
        build: smb-volume-k8s-release/smb-broker

- name: pats
  plan:
    - in_parallel:
        fail_fast: true
        steps:
          - get: smb-volume-k8s-release
            passed:
              - build-smb-broker-docker-image
            trigger: true
          - get: cf-volume-services-acceptance-tests
          - get: persi-ci
    - task: generate-pats-config
      file: persi-ci/scripts/ci/generate_pats_config.build.yml
      params:
        APPS_DOMAIN: app.cf.ephemeral-eirini-gke-2.cf-app.com
        CF_API_ENDPOINT: api.app.cf.ephemeral-eirini-gke-2.cf-app.com
        CF_USERNAME: admin
        CF_ADMIN_PASSWORD: ((eirini_cf_admin_password))
        BIND_CONFIG: '["{\"mount\":\"/home/vcap/data\"}"]'
        CREATE_BOGUS_CONFIG: ''
        CREATE_CONFIG: '{"share":"can-be-anything-for-now"}'
        PLAN_NAME: Existing
        SERVICE_NAME: SMB
    - task: run-pats
      file: persi-ci/scripts/ci/run-pats.build.yml
      attempts: 3
      params:
        PARALLEL_NODES: 2
        TEST_MOUNT_FAIL_LOGGING: false
        TEST_MOUNT_OPTIONS: false
        TEST_MULTI_CELL: false
        TEST_READ_ONLY: false