groups:
- name: all-jobs
  jobs:
  - smb-broker-unit-tests
  - build-smb-broker-docker-image
  - acquire-lock-ephemeral-eirini-env
  - deploy-ephemeral-eirini-env
  - undeploy-ephemeral-eirini-env

resources:
- name: smb-volume-k8s-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/smb-volume-k8s-release
    branch: master
    private_key: {{smb-broker-k8s-github-deploy-key}}

- name: smb-broker-docker-image
  type: docker-image
  source:
    repository: cfpersi/smb-broker
    username: ((dockerhub_username))
    password: ((dockerhub_password))


- name: smb-broker-version
  type: semver
  source:
    access_key_id: {{smb-broker-k8s-uploader_aws_ID}}
    bucket: smb-broker-versions-k8s
    initial_version: 0.0.0
    key: current-version
    region_name: us-east-1
    secret_access_key: {{smb-broker-k8s-uploader_aws_secret}}

- name: eirini-env
  type: git
  source:
    uri: git@github.com:cloudfoundry/gorgophone-env.git
    branch: master
    private_key: {{deployments-persi-key}}

- name: persi-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git

- name: ephemeral-eirini-env-gate-lock
  type: pool
  source:
    uri: git@github.com:cloudfoundry/gorgophone-env.git
    branch: master
    pool: gate-locks
    private_key: {{deployments-persi-key}}

jobs:
- name: smb-broker-unit-tests
  plan:
    - get: smb-volume-k8s-release
      trigger: true
    - task: unit-tests
      file: smb-volume-k8s-release/smb-broker/ci/unit-tests.yml
      privileged: true
    - get: smb-broker-version
      params:
        bump: minor
    - put: smb-volume-k8s-release
      params:
        repository: smb-volume-k8s-release
        tag: smb-broker-version/version
        only_tag: true
    - put: smb-broker-version
      params:
        bump: minor


- name: build-smb-broker-docker-image
  plan:
    - get: smb-volume-k8s-release
      passed:
      - smb-broker-unit-tests
      trigger: true
    - get: smb-broker-version
      passed:
      - smb-broker-unit-tests
    - put: smb-broker-docker-image
      params:
        tag_file: smb-broker-version/version
        tag_as_latest: true
        build: smb-volume-k8s-release/smb-broker

- name: acquire-lock-ephemeral-eirini-env
  build_logs_to_retain: 100
  serial: true
  plan:
    - in_parallel:
        fail_fast: true
        steps:
          - get: persi-ci
          - get: eirini-env
            trigger: true
    - put: ephemeral-eirini-env-gate-lock
      params:
        claim: ephemeral-eirini-env
      timeout: 3h

- name: deploy-ephemeral-eirini-env
  plan:
    - get: ephemeral-eirini-env-gate-lock
      passed:
        - acquire-lock-ephemeral-eirini-env
      trigger: true
    - get: persi-ci
    - get: eirini-env
    - task: deploy
      file: persi-ci/scripts/ci/deploy-eirini.build.yml
      params:
        GOOGLE_PROJECT_ID: ((gcp_project))
        GOOGLE_SERVICE_KEY: ((gcp_service_account_key))
        GIT_USER: {{github-user}}
        GIT_EMAIL: {{github-email}}
    - put: eirini-env
      attempts: 3
      params:
        repository: updated-eirini-env
        rebase: true
    - task: healthcheck
      file: persi-ci/scripts/ci/healthcheck-eirini.build.yml
      params:
        GOOGLE_PROJECT_ID: ((gcp_project))
        GOOGLE_SERVICE_KEY: ((gcp_service_account_key))
    - put: ephemeral-eirini-env-gate-lock
      attempts: 3
      params:
        release: ephemeral-eirini-env-gate-lock

- name: undeploy-ephemeral-eirini-env
  plan:
    - get: persi-ci
    - task: undeploy
      file: persi-ci/scripts/ci/undeploy-eirini.build.yml
      params:
        GOOGLE_PROJECT_ID: ((gcp_project))
        GOOGLE_SERVICE_KEY: ((gcp_service_account_key))
