#! this pipeline is deprecated and only kept in case that we need to bring it back
#! as of 10/04/2024 none of these images should still be used in our CI. 






---
#!  This pipeline is manually set
#!
#!  To set pipeline manually run:
#!    fly set-pipeline -p volume-services-docker-image-build -c docker-image-build.yml

# ************************************
# Secrets we need to run this pipeline
# ************************************

dockerhub_username: &dockerhub_username ((dockerhub.username))
dockerhub_password: &dockerhub_password ((dockerhub.password))
# Used to upload to docker hub the images built by this pipeline. The password is set via the dockerhub UI.

# **************
# End of secrets
# **************

resources:

- name: nightly
  type: time
  source:
    start: 12:00 AM
    stop: 1:00 AM
    location: America/Los_Angeles

- name: persi-ci
  type: git
  source:
    paths:
    - dockerfiles/*
    uri: https://github.com/cloudfoundry/persi-ci
    branch: master

- name: mapfs-tests-docker-image
  type: docker-image
  source:
    repository: cfpersi/mapfs-tests
    username: *dockerhub_username
    password: *dockerhub_password

- name: nfs-driver-integration-tests-docker-image
  type: docker-image
  source:
    repository: cfpersi/nfs-integration-tests
    username: *dockerhub_username
    password: *dockerhub_password

- name: bosh-release-test-docker-image
  type: docker-image
  source:
    repository: cfpersi/bosh-release-tests
    username: *dockerhub_username
    password: *dockerhub_password

- name: nfs-unit-tests-docker-image
  type: docker-image
  source:
    repository: cfpersi/nfs-unit-tests
    username: *dockerhub_username
    password: *dockerhub_password

- name: smb-unit-tests-docker-image
  type: docker-image
  source:
    repository: cfpersi/smb-unit-tests
    username: *dockerhub_username
    password: *dockerhub_password

- name: nfs-cats-docker-image
  type: docker-image
  source:
    repository: cfpersi/nfs-cats
    username: *dockerhub_username
    password: *dockerhub_password

- name: smb-volume-release
  type: git
  source:
    paths:
    - dockerfiles/*
    branch: master
    uri: https://github.com/cloudfoundry/smb-volume-release.git

- name: nfs-volume-release
  type: git
  source:
    paths:
    - dockerfiles/*
    branch: master
    uri: https://github.com/cloudfoundry/nfs-volume-release.git

- name: mapfs-release
  type: git
  source:
    paths:
    - dockerfiles/*
    branch: master
    uri: https://github.com/cloudfoundry/mapfs-release.git

jobs:

- name: build-nfs-driver-integration-tests-docker-image
  plan:
  - get: nightly
    trigger: true
  - get: nfs-volume-release
    trigger: true
  - put: nfs-driver-integration-tests-docker-image
    params:
      build: nfs-volume-release/dockerfiles/nfs-integration-tests

- name: build-bosh-release-test-docker-image
  plan:
  - get: nightly
    trigger: true
  - get: persi-ci
    trigger: true
  - put: bosh-release-test-docker-image
    params:
      build: persi-ci/dockerfiles/bosh-release-tests

- name: build-nfs-unit-tests-docker-image
  plan:
  - get: nightly
    trigger: true
  - get: nfs-volume-release
    trigger: true
  - put: nfs-unit-tests-docker-image
    params:
      build: nfs-volume-release/dockerfiles/nfs-unit-tests

- name: build-nfs-cats-docker-image
  plan:
  - get: nightly
    trigger: true
  - get: nfs-volume-release
    trigger: true
  - put: nfs-cats-docker-image
    params:
      build: nfs-volume-release/dockerfiles/nfs-cats

- name: build-mapfs-tests-docker-image
  plan:
  - get: nightly
    trigger: true
  - get: mapfs-release
    trigger: true
  - put: mapfs-tests-docker-image
    params:
      build: mapfs-release/dockerfiles/tests

- name: build-smb-unit-tests-docker-image
  plan:
  - get: nightly
    trigger: true
  - get: smb-volume-release
    trigger: true
  - put: smb-unit-tests-docker-image
    params:
      build: smb-volume-release/dockerfiles/smb-unit-tests
