groups:
- name: efs-tile
  jobs:
  - build-efs-broker-tile
  - build-vpn-client-tile
  - acquire-lock-efstile
  - bbl-up-efstile
  - bosh-deploy-openvpn
  - claim-toolsmiths-env
  # - upload-tiles-and-stemcell
  # - configure-efs-broker-tile
  # - configure-vpn-client-tile
  # - apply-changes
  # - pats-efs
  - unclaim-toolsmiths-env
  - bosh-delete-openvpn
  - bbl-destroy-efstile

- name: build
  jobs:
  - build-efs-broker-tile
  - build-vpn-client-tile

- name: test
  jobs:
  - acquire-lock-efstile
  - bbl-up-efstile
  - bosh-deploy-openvpn
  - claim-toolsmiths-env
#   - upload-tiles-and-stemcell
#   - configure-efs-broker-tile
#   - configure-vpn-client-tile
#   - apply-changes
#   - pats-efs
  - unclaim-toolsmiths-env
  - bosh-delete-openvpn
  - bbl-destroy-efstile

resource_types:
- name: pcf-pool
  type: docker-image
  source:
    repository: cftoolsmiths/toolsmiths-envs-resource
    tag: latest

- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
## General ##
- name: bosh-bootloader
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-bootloader.git

- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git

- name: env-creation-gate-lock
  type: pool
  source:
    uri: git@github.com:cloudfoundry/gorgophone-env.git
    branch: master
    pool: gate-locks
    private_key: {{deployments-persi-key}}

- name: gorgophone-env-director-state
  type: git
  source:
    uri: git@github.com:cloudfoundry/gorgophone-env.git
    branch: master
    private_key: {{deployments-persi-key}}

- name: kiln-concourse-tasks
  type: git
  source:
    branch: master
    uri: git@github.com:davewalter/kiln-concourse-tasks.git
    private_key: {{deployments-persi-key}}

- name: openvpn-bosh-release
  type: git
  source:
    branch: master
    uri: https://github.com/paulcwarren/openvpn-bosh-release.git

- name: pcf-2.5
  type: pcf-pool
  tags:
    - cf-diego-persistence-vsphere
  source:
    hostname: environments.toolsmiths.cf-app.com
    api_token: ((persi_toolsmiths_env_api_token))
    pool_name: us_2_5

- name: persi-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry/persi-ci.git
    branch: master
    private_key: {{deployments-persi-key}}
## End General ##

## Releases ##
- name: bpm-release-tarball
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/bpm-release

- name: efs-volume-release-tarball
  type: s3
  source:
    bucket: efs-volume-release-tarballs
    regexp: efs-volume-(.*).tgz
    access_key_id: {{efsvolume-reader_aws_ID}}
    secret_access_key: {{efsvolume-reader_aws_secret}}

- name: openvpn-release-tarball
  type: bosh-io-release
  source:
    repository: dpb587/openvpn-bosh-release

- name: routing-release-tarball
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/cf-routing-release
## End Releases ##

## Stemcell ##
- name: stemcell-linux-xenial
  type: pivnet
  source:
    api_token: ((persi_pivnet_refresh_token))
    product_slug: stemcells-ubuntu-xenial
    product_version: ^250\.\d+
    sort_by: semver
## End Stemcell ##

## EFS Broker Tile ##
- name: efs-broker-tile-bucket
  type: s3
  source:
    access_key_id: ((tile_manager_aws_access_key_id))
    secret_access_key: ((tile_manager_aws_secret_access_key))
    bucket: efs-broker-tiles
    private: true
    region_name: us-west-2
    regexp: efs-broker-(.*).pivotal

- name: efs-broker-tile-metadata-repo
  type: git
  source:
    uri: git@github.com:davewalter/aws-efs-broker-tile.git
    branch: master
    private_key: {{deployments-persi-key}}
    ignore_paths:
    - version

- name: efs-broker-tile-version
  type: semver
  source:
    driver: git
    uri: git@github.com:davewalter/aws-efs-broker-tile.git
    branch: master
    file: version
    initial_version: 0.0.1-build.1
    private_key: {{deployments-persi-key}}
## End EFS Broker Tile ##

## VPN Client Tile ##
- name: vpn-client-tile-bucket
  type: s3
  source:
    access_key_id: ((tile_manager_aws_access_key_id))
    secret_access_key: ((tile_manager_aws_secret_access_key))
    bucket: vpn-client-tiles
    private: true
    region_name: us-west-2
    regexp: vpn-client-(.*).pivotal

- name: vpn-client-tile-metadata-repo
  type: git
  source:
    uri: git@github.com:davewalter/aws-efs-broker-vpn-client-tile.git
    branch: master
    private_key: {{deployments-persi-key}}
    ignore_paths:
    - version

- name: vpn-client-tile-version
  type: semver
  source:
    driver: git
    uri: git@github.com:davewalter/aws-efs-broker-vpn-client-tile.git
    branch: master
    file: version
    initial_version: 0.0.1-build.1
    private_key: {{deployments-persi-key}}
## End VPN Client Tile ##

jobs:
- name: build-efs-broker-tile
  serial: true
  plan:
  - aggregate:
    - get: bpm-release-tarball
      params:
        tarball: true
      trigger: true
    - get: efs-volume-release-tarball
      trigger: true
    - get: kiln-concourse-tasks
    - get: metadata-repo
      resource: efs-broker-tile-metadata-repo
      trigger: true
    - get: routing-release-tarball
      params:
        tarball: true
      trigger: true
    - get: stemcell
      resource: stemcell-linux-xenial
      params:
        globs:
        - '*google*'
      trigger: true
    - get: version
      resource: efs-broker-tile-version
  - task: collect-bpm-release
    file: kiln-concourse-tasks/collect-release/task.yml
    input_mapping:
      base-releases: efs-volume-release-tarball
      new-release: bpm-release-tarball
    params:
      RELEASE_NAME: bpm
  - task: collect-routing-release
    file: kiln-concourse-tasks/collect-release/task.yml
    input_mapping:
      base-releases: collected-releases
      new-release: routing-release-tarball
    params:
      RELEASE_NAME: routing
  - task: create-tile
    file: kiln-concourse-tasks/bake/task.yml
    input_mapping:
      releases: collected-releases
    params:
      TILE_FILENAME_PREFIX: efs-broker
  - put: efs-broker-tile-version
    params:
      pre: build
  - put: efs-broker-tile-bucket
    params:
      file: tile/*.pivotal
    get_params:
      skip_download: 'true'

- name: build-vpn-client-tile
  serial: true
  plan:
  - aggregate:
    - get: kiln-concourse-tasks
    - get: metadata-repo
      resource: vpn-client-tile-metadata-repo
      trigger: true
    - get: openvpn-release-tarball
      params:
        tarball: true
      trigger: true
    - get: stemcell
      resource: stemcell-linux-xenial
      params:
        globs:
        - '*google*'
      trigger: true
    - get: version
      resource: vpn-client-tile-version
  - task: create-tile
    file: kiln-concourse-tasks/bake/task.yml
    input_mapping:
      releases: openvpn-release-tarball
    params:
      ICON_FILENAME: icon.jpg
      TILE_FILENAME_PREFIX: vpn-client
  - put: vpn-client-tile-version
    params:
      pre: build
  - put: vpn-client-tile-bucket
    params:
      file: tile/*.pivotal
    get_params:
      skip_download: 'true'

- name: acquire-lock-efstile
  serial: true
  plan:
  - aggregate:
    - get: efs-broker-tile-bucket
      passed:
      - build-efs-broker-tile
      trigger: true
    - get: vpn-client-tile-bucket
      passed:
      - build-vpn-client-tile
      trigger: true
  - put: env-creation-gate-lock
    params:
      claim: efstile
    timeout: 3h

- name: bbl-up-efstile
  plan:
  - aggregate:
    - get: bosh-bootloader
    - get: cf-deployment-concourse-tasks
    - get: efs-broker-tile-bucket
      passed:
      - acquire-lock-efstile
    - get: env-creation-gate-lock
      passed:
      - acquire-lock-efstile
      trigger: true
    - get: gorgophone-env-director-state
    - get: persi-ci
    - get: vpn-client-tile-bucket
      passed:
      - acquire-lock-efstile
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: aws
      BBL_AWS_ACCESS_KEY_ID: {{gorgophone_aws_access_key_id}}
      BBL_AWS_SECRET_ACCESS_KEY: {{gorgophone_aws_secret_access_key}}
      BBL_AWS_REGION: us-west-1
      BBL_STATE_DIR: bbl-state-aws-efstile
      BBL_ENV_NAME: efstile
      GIT_COMMIT_EMAIL: cf-diego-persistence@pivotal.io
      SKIP_LB_CREATION: true
      BBL_CONFIG_DIR: plan-patches/openvpn-aws
    input_mapping:
      bbl-state: gorgophone-env-director-state
      bbl-config: bosh-bootloader
    ensure:
      put: gorgophone-env-director-state
      params:
        repository: updated-bbl-state
        rebase: true

- name: bosh-deploy-openvpn
  plan:
  - aggregate:
    - get: openvpn-bosh-release
    - get: cf-deployment-concourse-tasks
    - get: env-creation-gate-lock
      passed:
      - bbl-up-efstile
    - get: gorgophone-env-director-state
      passed:
      - bbl-up-efstile
      trigger: true
    - get: persi-ci
    - get: efs-broker-tile-bucket
      passed:
      - bbl-up-efstile
    - get: vpn-client-tile-bucket
      passed:
      - bbl-up-efstile
  - task: collect-openvpn-ops-files
    file: cf-deployment-concourse-tasks/collect-ops-files/task.yml
    input_mapping:
      base-ops-files: openvpn-bosh-release
      new-ops-files: persi-ci
    params:
      BASE_OPS_FILE_DIR: "deployment"
      NEW_OPS_FILES: "operations/with-bosh-agent.yml \
                      operations/with-static-ip.yml \
                      operations/with-vpn-client-cert.yml"
  - task: generate-variables
    file: persi-ci/scripts/ci/generate-openvpn-variables.build.yml
    input_mapping:
      director-state: gorgophone-env-director-state
    params:
      AWS_ACCESS_KEY_ID: {{gorgophone_aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{gorgophone_aws_secret_access_key}}
      BBL_STATE_DIR: bbl-state-aws-efstile
  - task: bosh-deploy-cf
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    input_mapping:
      bbl-state: gorgophone-env-director-state
      cf-deployment: openvpn-bosh-release
      ops-files: collected-ops-files
      vars-files: generated-var-files
    params:
      BBL_STATE_DIR: bbl-state-aws-efstile
      MANIFEST_FILE: deployment/openvpn.yml
      SYSTEM_DOMAIN: dummy.persi.cf-app.com
      VARS_FILES: "openvpn-vars.yml"
      OPS_FILES: "deployment/with-lan-access.yml \
                  deployment/with-lan-masquerading.yml \
                  deployment/with-multiple-client-connections.yml \
                  deployment/with-bosh-agent.yml \
                  deployment/with-static-ip.yml \
                  deployment/with-vpn-client-cert.yml"

- name: claim-toolsmiths-env
  plan:
  - aggregate:
    - get: env-creation-gate-lock
    - get: efs-broker-tile-bucket
      passed:
      - acquire-lock-efstile
    - get: vpn-client-tile-bucket
      passed:
      - acquire-lock-efstile
  - put: pcf-2.5
    tags:
      - cf-diego-persistence-vsphere
    params:
      action: claim

- name: unclaim-toolsmiths-env
  plan:
  - aggregate:
    - get: gorgophone-env-director-state
      passed:
      - bbl-up-efstile
    - get: env-creation-gate-lock
      passed:
      - claim-toolsmiths-env
    - get: pcf-2.5
      tags:
        - cf-diego-persistence-vsphere
      passed:
      - claim-toolsmiths-env
  - put: pcf-2.5
    tags:
      - cf-diego-persistence-vsphere
    params:
      action: unclaim
      env_file: pcf-2.5/metadata

- name: bosh-delete-openvpn
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: env-creation-gate-lock
      passed:
      - unclaim-toolsmiths-env
    - get: gorgophone-env-director-state
      passed:
      - unclaim-toolsmiths-env
      trigger: true
  - task: delete-openvpn
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    params:
      BBL_STATE_DIR: bbl-state-aws-efstile
      DEPLOYMENT_NAME: openvpn
    input_mapping:
      bbl-state: gorgophone-env-director-state

- name: bbl-destroy-efstile
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: env-creation-gate-lock
      passed:
      - bosh-delete-openvpn
    - get: gorgophone-env-director-state
      passed:
      - bosh-delete-openvpn
      trigger: true
  - task: destroy
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    params:
      BBL_STATE_DIR: bbl-state-aws-efstile
      GIT_COMMIT_EMAIL: cf-diego-persistence@pivotal.io
      BBL_AWS_ACCESS_KEY_ID: {{gorgophone_aws_access_key_id}}
      BBL_AWS_SECRET_ACCESS_KEY: {{gorgophone_aws_secret_access_key}}
    input_mapping:
      bbl-state: gorgophone-env-director-state
    ensure:
      put: gorgophone-env-director-state
      params:
        repository: updated-bbl-state
        rebase: true
  - put: env-creation-gate-lock
    params:
      release: env-creation-gate-lock
