---
#  This pipeline is set automatics, any none committed changes will be lost.
#
# To set the pipeline, run:
#    fly -t cryo-runway set-pipeline -p lts-nfsbroker-v5.0 -c lts-nfsbroker-v5.0.yml
#
# ************************************
# Secrets we need to run this pipeline
# ************************************

#! this needs to come first, else all other vars can't be resolved.
#! cerberus creds are required to access the teams vault instance managed by cerberus. The creds have been created manually via the vault-cli targetting the teams cerberus vault. Example steps to create an approle are here: https://developer.hashicorp.com/vault/docs/auth/approle the required value for policies is `restricted-admin` the auth method is mounted on the standard path.
cerberus: &cerberus
  role_id: ((cerberus-auth.role_id))
  secret_id: ((cerberus-auth.secret_id))
cerberus_url: &cerberus_url ((cerberus-auth.url))
github_ssh_key: &github_ssh_key ((cerberus:github.ssh_key))
github_access_token: &github_access_token ((cerberus:github.access_token))
# used to get pull requests and get git repos

# **************
# End of secrets
# **************
var_sources:
- name: cerberus
  type: vault
  config:
    auth_backend: approle
    auth_params: *cerberus
    url: *cerberus_url
    path_prefix: secret

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/cryogenics/pr-queue-resource

resources:
- name: persi-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git
    branch: master

- name: nfsbroker
  type: pull-request
  source:
    repository: cloudfoundry/nfsbroker
    base_branch: v5.0
    disable_forks: true
    access_token: *github_access_token

- name: credhub
  type: git
  source:
    branch: main
    uri: https://github.com/cloudfoundry-incubator/credhub

- name: image-nfs-unit-tests
  type: docker-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/cfpersi/nfs-unit-tests
    tag: latest

jobs:
- name: security-scan
  plan:
  - in_parallel:
    - get: persi-ci
    - get: image-nfs-unit-tests
    - get: nfsbroker
      trigger: true
  - task: build
    image: image-nfs-unit-tests
    file: persi-ci/scripts/ci/security-scan.build.yml
    params:
      PATHS: "./"
    input_mapping:
      release-dir: nfsbroker

- name: unit-and-integration-test
  public: true
  plan:
  - in_parallel:
    - get: nfsbroker
      trigger: true
    - get: credhub
  - task: build
    file: nfsbroker/scripts/ci/run_unit_and_integration.build.yml

- name: merge-pr
  plan:
  - get: nfsbroker
    trigger: true
    passed:
    - security-scan
    - unit-and-integration-test
  - put: nfsbroker
    params:
      merge: true
      repository: nfsbroker
