---
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: cryogenics/pr-queue-resource

resources:
- name: nfsv3driver
  type: pull-request
  source:
    repository: cloudfoundry/nfsv3driver
    base_branch: v5.0
    disable_forks: true
    access_token: ((github.access_token))

- name: persi-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git
    branch: master

- name: mapfs
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/mapfs.git
    private_key: ((github.ssh_key))

- name: docker_driver_integration_tests
  type: git
  source:
    branch: main
    uri: https://github.com/cloudfoundry/docker_driver_integration_tests

jobs:
- name: unit-test
  public: true
  plan:
  - get: nfsv3driver
    trigger: true
  - task: build
    file: nfsv3driver/scripts/ci/run_unit.build.yml

- name: security-scan
  plan:
  - in_parallel:
    - get: persi-ci
    - get: nfsv3driver
      trigger: true
      passed:
      - unit-test
  - task: build
    file: persi-ci/scripts/ci/security-scan.build.yml
    params:
      PATHS: "./"
    input_mapping:
      release-dir: nfsv3driver

- name: integration
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: docker_driver_integration_tests
      - get: nfsv3driver
        passed:
        - unit-test
        trigger: true
      - get: mapfs
  - in_parallel:
      fail_fast: true
      steps:
      - task: run_docker_driver_integration_tests
        file: nfsv3driver/scripts/ci/run_docker_driver_integration_tests.build.yml
        privileged: true
        params:
          TEST_PACKAGE: docker_driver_integration_tests/
      - task: run_docker_driver_lazy_unmount_integration_tests
        file: nfsv3driver/scripts/ci/run_docker_driver_integration_tests.build.yml
        privileged: true
        params:
          TEST_PACKAGE: docker_driver_integration_tests/lazy_unmount
      - task: run_driver_broker_compatibility_tests
        file: nfsv3driver/scripts/ci/run_docker_driver_integration_tests.build.yml
        privileged: true
        params:
          TEST_PACKAGE: docker_driver_integration_tests/compatibility

- name: merge-pr
  serial: true
  plan:
  - get: nfsv3driver
    trigger: true
    passed:
    - security-scan
    - integration
  - put: nfsv3driver
    params:
      merge: true
      repository: nfsv3driver
