resources:
- name: mapfs
  type: git
  source:
    uri: https://github.com/cloudfoundry/mapfs.git

- name: mapfs-release
  type: git
  source:
    branch: master
    username: {{github-user}}
    password: {{github-password}}
    uri: https://github.com/cloudfoundry/mapfs-release.git

- name: persi-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git

jobs:
- name: unit-test
  public: true
  plan:
  - get: mapfs
    trigger: true
  - task: build
    file: mapfs/scripts/ci/run_unit.build.yml
    privileged: true

- name: security-scan
  plan:
    - in_parallel:
        - get: persi-ci
        - get: mapfs
          trigger: true
    - task: build
      file: persi-ci/scripts/ci/security-scan.build.yml
      params:
        PATHS: "./"
      input_mapping:
        release-dir: mapfs

- name: bump-submodule
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: mapfs-release
      - get: mapfs
        passed:
        - unit-test
        - security-scan
        trigger: true
  - task: bump-submodule
    file: persi-ci/scripts/ci/bump_submodule.build.yml
    input_mapping:
      release-repo: mapfs-release
      submodule-repo: mapfs
    params:
      SUBMODULE_PATH: src/mapfs
  - put: mapfs-release
    params:
      repository: bumped-repo
      rebase: true
