---
#!  This pipeline is set automatically, any uncommitted changes will be lost.
#!
#! To set the pipeline manually, run:
#!    fly -t cryo-runway set-pipeline -p mapfs -c mapfs.yml
#!
#! ************************************
#! Secrets we need to run this pipeline
#! ************************************
#! this needs to come first, otherwise all other vars can't be resolved.
#! cerberus creds are required to access the teams vault instance managed by cerberus. The creds have been created
#! manually via the vault-cli targeting the teams cerberus vault. Example steps to create an approle are here:
#! https://developer.hashicorp.com/vault/docs/auth/approle the required value for policies is `restricted-admin` the
#! auth method is mounted on the standard path.
cerberus: &cerberus
  role_id: ((cerberus-auth.role_id))
  secret_id: ((cerberus-auth.secret_id))
cerberus_url: &cerberus_url ((cerberus-auth.url))

cerberus_secrets:
#! used to manage pull requests
- &github_access_token ((cerberus:github.access_token))
#! GitHub SSH key is used to gain write access to the repository
- &github_ssh_key ((cerberus:github.ssh_key))
#! GitHub email and username are used to sign the commits and PRs for go module auto bumps. Added 2024-02-12
- &github_user ((cerberus:github.user))
- &github_email ((cerberus:github.email))

#! gcr_viewer_key was needed on 2024-03-24 for getting concourse container images from our GCR instance. Generated by using personal creds to log into the mapbu-cryogenics google cloud project.
- &gcr_viewer_key  ((cerberus:gcr.viewer_key))

#! **************
#! End of secrets
#! **************
var_sources:
- name: cerberus
  type: vault
  config:
    auth_backend: approle
    auth_params: *cerberus
    url: *cerberus_url
    path_prefix: secret

groups:
- name: test
  jobs:
  - unit-test
  - fs-test
  - security-scan
  - merge-pr
- name: update
  jobs:
  - bump-go-module

resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: us-west2-docker.pkg.dev/mapbu-cryogenics/concourse-resources/pr-queue-resource
    username: _json_key
    password: *gcr_viewer_key

resources:
- name: mapfs
  type: pull-request
  icon: source-pull
  source:
    repository: cloudfoundry/mapfs
    base_branch: master
    disable_forks: true
    access_token: *github_access_token

- name: mapfs-read
  type: git
  icon: github
  source:
    uri: https://github.com/cloudfoundry/mapfs
    branch: master

- name: mapfs-write
  type: git
  icon: git
  source:
    uri: git@github.com:cloudfoundry/mapfs.git
    private_key: *github_ssh_key
    commit_filter:
      exclude:
      - ;resource comment; This resource is used exclusively for pushing new changes

- name: cryogenics-concourse-tasks
  type: git
  icon: github
  source:
    uri: git@github.com:pivotal/cryogenics-concourse-tasks.git
    private_key: *github_ssh_key
    branch: main

- name: image-cryogenics-essentials
  icon: docker
  type: registry-image
  source:
    repository: us-west2-docker.pkg.dev/mapbu-cryogenics/essentials/cryo-essentials
    username: _json_key
    password: *gcr_viewer_key
    tag: latest

- name: cfpersi-nfs-integration-tests
  icon: docker
  type: registry-image
  source:
    repository: us-west2-docker.pkg.dev/mapbu-cryogenics/dockerhub-proxy-cache/cfpersi/nfs-integration-tests
    username: _json_key
    password: *gcr_viewer_key
    tag: latest

- name: cfpersi-mapfs-tests
  icon: docker
  type: registry-image
  source:
    repository: us-west2-docker.pkg.dev/mapbu-cryogenics/dockerhub-proxy-cache/cfpersi/mapfs-tests
    username: _json_key
    password: *gcr_viewer_key
    tag: latest

- name: fstest
  type: git
  source:
    uri: https://github.com/zfsonlinux/fstest.git
    branch: master

- name: persi-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git
    branch: master

- name: once-a-week
  type: time
  icon: clock-outline
  source:
    days: [ Monday ]

jobs:
- name: unit-test
  public: true
  plan:
  - get: mapfs
    trigger: true
  - get: cfpersi-nfs-integration-tests
  - task: build
    image: cfpersi-nfs-integration-tests
    file: mapfs/scripts/ci/run_unit.build.yml
    privileged: true

- name: fs-test
  public: true
  plan:
  - get: mapfs
    trigger: true
  - get: fstest
  - get: cfpersi-mapfs-tests
  - task: build
    image: cfpersi-mapfs-tests
    file: mapfs/scripts/ci/run_fstest.build.yml
    privileged: true

- name: security-scan
  plan:
  - in_parallel:
    - get: persi-ci
    - get: image-cryogenics-essentials
    - get: mapfs
      trigger: true
  - task: build
    image: image-cryogenics-essentials
    file: persi-ci/scripts/ci/security-scan.build.yml
    params:
      PATHS: "./"
    input_mapping:
      release-dir: mapfs

- name: merge-pr
  plan:
  - get: mapfs
    trigger: true
    passed:
    - unit-test
    - fs-test
    - security-scan
  - put: mapfs
    params:
      merge: true
      repository: mapfs
- name: bump-go-module
  plan:
  - in_parallel:
    - get: source-repo
      resource: mapfs-read
    - get: cryogenics-concourse-tasks
    - get: image-cryogenics-essentials
    - get: once-a-week
      trigger: true
  - task: bump-go-module
    image: image-cryogenics-essentials
    file: cryogenics-concourse-tasks/deps-automation/bump-go-module/task.yml
    params:
      GIT_USERNAME: *github_user
      GIT_EMAIL: *github_email
      ROOT_DIRECTORIES: .
  - try:
      load_var: go-module-update-branch
      file: destination-repo/.update-branch-name
      on_success:
        do:
        - put: mapfs-write
          params:
            repository: destination-repo
            branch: &go-module-branch ((.:go-module-update-branch))
        - task: create-go-module-bump-pull-request
          image: image-cryogenics-essentials
          file: cryogenics-concourse-tasks/github-automation/create-pr/task.yml
          params:
            BASE: master
            BRANCH: *go-module-branch
            LABELS: dependencies
            TITLE: Bump go module ((.:go-module-update-branch))
            MESSAGE: |
              This is an automatically generated Pull Request from the Cryogenics CI Bot.

              I have detected a new version of a go module and automatically bumped
              it to benefit from the latest changes.

              If this does not look right, please reach out to the [#mapbu-cryogenics](https://vmware.slack.com/archives/C01DXEYRKRU) team.
          input_mapping:
            source-repo: mapfs-write
