---
#  This pipeline is set automatics, any none committed changes will be lost.
#
# To set the pipeline, run:
#    fly -t cryo-runway set-pipeline -p mapfs -c mapfs.yml
#
# ************************************
# Secrets we need to run this pipeline
# ************************************

github_access_token: &github_access_token ((github.access_token))
# used to get pull requests

# **************
# End of secrets
# **************

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/cryogenics/pr-queue-resource

resources:
- name: mapfs
  type: pull-request
  source:
    repository: cloudfoundry/mapfs
    base_branch: master
    disable_forks: true
    access_token: *github_access_token

- name: fstest
  type: git
  source:
    uri: https://github.com/zfsonlinux/fstest.git
    branch: master

- name: persi-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git
    branch: master

- name: image-nfs-unit-tests
  type: docker-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/cfpersi/nfs-unit-tests
    tag: latest

jobs:
- name: unit-test
  public: true
  plan:
  - get: mapfs
    trigger: true
  - task: build
    file: mapfs/scripts/ci/run_unit.build.yml
    privileged: true

- name: fs-test
  public: true
  plan:
  - get: mapfs
    trigger: true
  - get: fstest
  - task: build
    file: mapfs/scripts/ci/run_fstest.build.yml
    privileged: true

- name: security-scan
  plan:
  - in_parallel:
    - get: persi-ci
    - get: image-nfs-unit-tests
    - get: mapfs
      trigger: true
  - task: build
    image: image-nfs-unit-tests
    file: persi-ci/scripts/ci/security-scan.build.yml
    params:
      PATHS: "./"
    input_mapping:
      release-dir: mapfs

- name: merge-pr
  plan:
  - get: mapfs
    trigger: true
    passed:
    - unit-test
    - fs-test
    - security-scan
  - put: mapfs
    params:
      merge: true
      repository: mapfs
