---
#  This pipeline is set automatically, any uncommitted changes will be lost.
#
# To set the pipeline manually, run:
#    fly -t cryo-runway set-pipeline -p mapfs -c mapfs.yml
#
# ************************************
# Secrets we need to run this pipeline
# ************************************
#! this needs to come first, otherwise all other vars can't be resolved.
#! cerberus creds are required to access the teams vault instance managed by cerberus. The creds have been created
#! manually via the vault-cli targeting the teams cerberus vault. Example steps to create an approle are here:
#! https://developer.hashicorp.com/vault/docs/auth/approle the required value for policies is `restricted-admin` the
#! auth method is mounted on the standard path.
cerberus: &cerberus
  role_id: ((cerberus-auth.role_id))
  secret_id: ((cerberus-auth.secret_id))
cerberus_url: &cerberus_url ((cerberus-auth.url))

cerberus_secrets:
- &github_access_token ((cerberus:github.access_token))
# used to manage pull requests
- &github_ssh_key ((cerberus:github.ssh_key))
#! GitHub SSH key is used to gain write access to the repository
- &github_user ((cerberus:github.user))
- &github_email ((cerberus:github.email))
#! GitHub email and username are used to sign the commits and PRs for go module auto bumps. Added 2024-02-12

# **************
# End of secrets
# **************
var_sources:
- name: cerberus
  type: vault
  config:
    auth_backend: approle
    auth_params: *cerberus
    url: *cerberus_url
    path_prefix: secret

groups:
- name: test
  jobs:
  - unit-test
  - fs-test
  - security-scan
  - merge-pr
- name: update
  jobs:
  - bump-go-module

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/cryogenics/pr-queue-resource

resources:
- name: mapfs-pr
  type: pull-request
  icon: source-pull
  source:
    repository: cloudfoundry/mapfs
    base_branch: master
    disable_forks: true
    access_token: *github_access_token

- name: mapfs-read
  type: git
  icon: github
  source:
    uri: https://github.com/cloudfoundry/mapfs
    branch: master

- name: mapfs-write
  type: git
  icon: git
  source:
    uri: git@github.com:cloudfoundry/mapfs.git
    private_key: *github_ssh_key
    commit_filter:
      exclude:
      - ;resource comment; This resource is used exclusively for pushing new changes

- name: cryogenics-concourse-tasks
  type: git
  icon: github
  source:
    uri: git@github.com:pivotal/cryogenics-concourse-tasks.git
    private_key: *github_ssh_key
    branch: main

- name: cryogenics-essentials
  icon: docker
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/cryogenics/essentials
    tag: latest

- name: fstest
  type: git
  source:
    uri: https://github.com/zfsonlinux/fstest.git
    branch: master

- name: persi-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git
    branch: master

- name: image-nfs-unit-tests
  type: docker-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/cfpersi/nfs-unit-tests
    tag: latest

- name: once-a-week
  type: time
  icon: clock-outline
  source:
    days: [ Monday ]

jobs:
- name: unit-test
  public: true
  plan:
  - get: mapfs-pr
    trigger: true
  - task: build
    file: mapfs-pr/scripts/ci/run_unit.build.yml
    privileged: true

- name: fs-test
  public: true
  plan:
  - get: mapfs-pr
    trigger: true
  - get: fstest
  - task: build
    file: mapfs-pr/scripts/ci/run_fstest.build.yml
    privileged: true

- name: security-scan
  plan:
  - in_parallel:
    - get: persi-ci
    - get: image-nfs-unit-tests
    - get: mapfs-pr
      trigger: true
  - task: build
    image: image-nfs-unit-tests
    file: persi-ci/scripts/ci/security-scan.build.yml
    params:
      PATHS: "./"
    input_mapping:
      release-dir: mapfs-pr

- name: merge-pr
  plan:
  - get: mapfs-pr
    trigger: true
    passed:
    - unit-test
    - fs-test
    - security-scan
  - put: mapfs-pr
    params:
      merge: true
      repository: mapfs-pr
- name: bump-go-module
  plan:
  - in_parallel:
    - get: source-repo
      resource: mapfs-read
    - get: cryogenics-concourse-tasks
    - get: cryogenics-essentials
    - get: once-a-week
      trigger: true
  - task: bump-go-module
    file: cryogenics-concourse-tasks/deps-automation/bump-go-module/task.yml
    image: cryogenics-essentials
    params:
      GIT_USERNAME: *github_user
      GIT_EMAIL: *github_email
      ROOT_DIRECTORIES: .
  - try:
      load_var: go-module-update-branch
      file: destination-repo/.update-branch-name
      on_success:
        do:
        - put: mapfs-write
          params:
            repository: destination-repo
            branch: &go-module-branch ((.:go-module-update-branch))
        - task: create-go-module-bump-pull-request
          file: cryogenics-concourse-tasks/github-automation/create-pr/task.yml
          image: cryogenics-essentials
          params:
            BASE: master
            BRANCH: *go-module-branch
            LABELS: dependencies
            TITLE: Bump go module ((.:go-module-update-branch))
            MESSAGE: |
              This is an automatically generated Pull Request from the Cryogenics CI Bot.

              I have detected a new version of a go module and automatically bumped
              it to benefit from the latest changes.

              If this does not look right, please reach out to the [#mapbu-cryogenics](https://vmware.slack.com/archives/C01DXEYRKRU) team.
          input_mapping:
            source-repo: mapfs-write
