resources:
- name: mapfs
  type: git
  source:
    uri: git@github.com:cloudfoundry/mapfs.git
    private_key: ((github.ssh_key))

- name: fstest
  type: git
  source:
    uri: https://github.com/zfsonlinux/fstest.git

- name: persi-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git
    branch: freezing

jobs:
- name: unit-test
  public: true
  plan:
  - get: mapfs
    trigger: true
  - task: build
    file: mapfs/scripts/ci/run_unit.build.yml
    privileged: true

- name: fs-test
  public: true
  plan:
  - get: mapfs
    trigger: true
  - get: fstest
  - task: build
    file: mapfs/scripts/ci/run_fstest.build.yml
    privileged: true

- name: security-scan
  plan:
    - in_parallel:
        - get: persi-ci
        - get: mapfs
          trigger: true
    - task: build
      file: persi-ci/scripts/ci/security-scan.build.yml
      params:
        PATHS: "./"
      input_mapping:
        release-dir: mapfs
