resource_types:
  - name: go-mod-vendor-tidy-git
    type: docker-image
    source:
      repository: cfpersi/fork-git-resource
      tag: latest

resources:
- name: nfsv3driver
  type: go-mod-vendor-tidy-git
  source:
    uri: git@github.com:cloudfoundry/nfsv3driver.git
    private_key: ((github.ssh_key))

- name: nfs-volume-release
  type: git
  source:
    branch: master
    private_key: ((github.ssh_key))
    uri: https://github.com/cloudfoundry/nfs-volume-release.git

- name: persi-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git
    branch: freezing

- name: mapfs
  type: go-mod-vendor-tidy-git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/mapfs.git
    private_key: ((github.ssh_key))

- name: mapfs-release
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/mapfs-release.git

- name: docker_driver_integration_tests
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/docker_driver_integration_tests

jobs:
- name: unit-test
  public: true
  plan:
  - get: nfsv3driver
    trigger: true
  - task: build
    file: nfsv3driver/scripts/ci/run_unit.build.yml

- name: security-scan
  plan:
    - in_parallel:
        - get: persi-ci
        - get: nfsv3driver
          trigger: true
    - task: build
      file: persi-ci/scripts/ci/security-scan.build.yml
      params:
        PATHS: "./"
      input_mapping:
        release-dir: nfsv3driver

- name: integration
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: docker_driver_integration_tests
      - get: nfsv3driver
        passed:
        - unit-test
        trigger: true
      - get: mapfs
  - in_parallel:
      fail_fast: true
      steps:
      - task: run_docker_driver_integration_tests
        file: nfsv3driver/scripts/ci/run_docker_driver_integration_tests.build.yml
        privileged: true
        params:
          TEST_PACKAGE: docker_driver_integration_tests/
      - task: run_docker_driver_lazy_unmount_integration_tests
        file: nfsv3driver/scripts/ci/run_docker_driver_integration_tests.build.yml
        privileged: true
        params:
          TEST_PACKAGE: docker_driver_integration_tests/lazy_unmount
      - task: run_driver_broker_compatibility_tests
        file: nfsv3driver/scripts/ci/run_docker_driver_integration_tests.build.yml
        privileged: true
        params:
          TEST_PACKAGE: docker_driver_integration_tests/compatibility

- name: release-job-tests
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: mapfs-release
      - get: nfs-volume-release
      - get: nfsv3driver
        passed:
        - integration
        - security-scan
        trigger: true
  - task: bump-submodule
    file: persi-ci/scripts/ci/bump_submodule.build.yml
    input_mapping:
      release-repo: nfs-volume-release
      submodule-repo: nfsv3driver
    params:
      SUBMODULE_PATH: src/code.cloudfoundry.org/nfsv3driver
  - task: rspec
    file: persi-ci/scripts/ci/run-rspec.build.yml
    input_mapping:
      test-repo: bumped-repo
  - task: bosh-release-test
    attempts: 3
    input_mapping:
      nfs-volume-release: bumped-repo
      nfs-volume-release-concourse-tasks: bumped-repo
    file: nfs-volume-release/scripts/ci/run_bosh_release_tests.build.yml
    privileged: true
  - put: nfs-volume-release
    params:
      repository: bumped-repo
      rebase: true
