resources:
- name: persi-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git
    branch: freezing

- name: nfsbroker
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/nfsbroker.git
    private_key: ((github.ssh_key))

- name: credhub
  type: git
  source:
    branch: main
    uri: https://github.com/cloudfoundry-incubator/credhub

jobs:
- name: security-scan
  plan:
    - in_parallel:
        - get: persi-ci
        - get: nfsbroker
          trigger: true
    - task: build
      file: persi-ci/scripts/ci/security-scan.build.yml
      params:
        PATHS: "./"
      input_mapping:
        release-dir: nfsbroker

- name: unit-and-integration-test
  public: true
  plan:
  - in_parallel:
    - get: nfsbroker
      trigger: true
    - get: credhub
  - task: build
    file: nfsbroker/scripts/ci/run_unit_and_integration.build.yml

