resource_types:
  - name: go-mod-vendor-tidy-git
    type: docker-image
    source:
      repository: cfpersi/fork-git-resource
      tag: latest

resources:
- name: persi-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git
    branch: freezing

- name: nfsbroker
  type: go-mod-vendor-tidy-git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/nfsbroker.git
    private_key: ((github.ssh_key))

- name: nfs-volume-release
  type: git
  source:
    branch: master
    private_key: ((github.ssh_key))
    uri: git@github.com:cloudfoundry/nfs-volume-release.git

- name: credhub
  type: git
  source:
    branch: main
    uri: https://github.com/cloudfoundry-incubator/credhub

- name: mapfs-release
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/mapfs-release.git

jobs:
- name: security-scan
  plan:
    - in_parallel:
        - get: persi-ci
        - get: nfsbroker
          trigger: true
    - task: build
      file: persi-ci/scripts/ci/security-scan.build.yml
      params:
        PATHS: "./"
      input_mapping:
        release-dir: nfsbroker

- name: unit-and-integration-test
  public: true
  plan:
  - in_parallel:
    - get: nfsbroker
      trigger: true
    - get: credhub
  - task: build
    file: nfsbroker/scripts/ci/run_unit_and_integration.build.yml

- name: release-job-tests
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: mapfs-release
      - get: nfs-volume-release
      - get: nfsbroker
        passed:
        - unit-and-integration-test
        - security-scan
        trigger: true
  - task: bump-submodule
    file: persi-ci/scripts/ci/bump_submodule.build.yml
    input_mapping:
      release-repo: nfs-volume-release
      submodule-repo: nfsbroker
    params:
      SUBMODULE_PATH: src/code.cloudfoundry.org/nfsbroker
  - task: rspec
    file: persi-ci/scripts/ci/run-rspec.build.yml
    input_mapping:
      test-repo: bumped-repo
  - task: bosh-release-test
    attempts: 3
    input_mapping:
      nfs-volume-release: bumped-repo
      nfs-volume-release-concourse-tasks: bumped-repo
    file: nfs-volume-release/scripts/ci/run_bosh_release_tests.build.yml
    privileged: true
  - put: nfs-volume-release
    params:
      repository: bumped-repo
      rebase: true
