---
#  This pipeline is set automatics, any none committed changes will be lost.
#
# To set the pipeline, run:
#    fly -t cryo set-pipeline -p nfsbroker -c nfsbroker.yml
#
# ************************************
# Secrets we need to run this pipeline
# ************************************

secrets:
#! GitHub SSH Key is used to push git commits and accessing repositories. Added 2024-02-19
- &github_access_token ((github-tas-runtime-bot/access-token))
- &github_ssh_key ((github-tas-runtime-bot/private-key))

#! GitHub email and username are used to sign the commits and PRs for go module auto bumps. Added 2024-02-19
- &github_user App Platform Runtime Working Group CI Bot
- &github_email tas-runtime.pdl+tas-runtime-bot@broadcom.com

- &gcr_viewer_key  ((gcp-tas-runtime-service-account/config-json))

# **************
# End of secrets
# **************

groups:
- name: test
  jobs:
  - security-scan
  - unit-and-integration-test
  - merge-pr
- name: bump
  jobs:
  - bump-go-module

resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: us-west2-docker.pkg.dev/mapbu-cryogenics/concourse-resources/pr-queue-resource
    username: _json_key
    password: *gcr_viewer_key

resources:
- name: persi-ci
  type: git
  icon: github
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git
    branch: master

- name: nfsbroker
  type: pull-request
  icon: source-pull
  source:
    repository: cloudfoundry/nfsbroker
    base_branch: &base_branch master
    disable_forks: true
    access_token: *github_access_token

- name: run-once-a-week
  type: time
  icon: timer-outline
  source:
    days: [ Thursday ]

- name: nfsbroker-repo
  type: git
  icon: github
  source:
    private_key: *github_ssh_key
    uri: &source-repo git@github.com:cloudfoundry/nfsbroker.git
    branch: *base_branch

- name: nfsbroker-repo-write
  type: git
  icon: github
  source:
    private_key: *github_ssh_key
    uri: *source-repo
    commit_filter:
      exclude:
      - ;resource comment; This resource is used exclusively for pushing new changes

- name: credhub
  type: git
  icon: github
  source:
    branch: main
    uri: https://github.com/cloudfoundry-incubator/credhub

- name: image-cryogenics-essentials
  type: registry-image
  icon: docker
  source:
    repository: us-west2-docker.pkg.dev/mapbu-cryogenics/essentials/cryo-essentials
    username: _json_key
    password: *gcr_viewer_key

- name: cryogenics-concourse-tasks
  type: git
  icon: github
  source:
    private_key: ((tas-runtime-bot-cryo-deploy-key-for-pivotal-org/private_key))
    uri: git@github.com:pivotal/cryogenics-concourse-tasks.git
    branch: main

jobs:
- name: security-scan
  plan:
  - in_parallel:
    - get: persi-ci
    - get: image-cryogenics-essentials
    - get: nfsbroker
      trigger: true
  - task: build
    image: image-cryogenics-essentials
    file: persi-ci/scripts/ci/security-scan.build.yml
    params:
      PATHS: "./"
    input_mapping:
      release-dir: nfsbroker

- name: unit-and-integration-test
  public: true
  plan:
  - in_parallel:
    - get: nfsbroker
      trigger: true
    - get: credhub
    - get: image-cryogenics-essentials
  - task: build
    image: image-cryogenics-essentials
    file: nfsbroker/scripts/ci/run_unit_and_integration.build.yml

- name: merge-pr
  plan:
  - get: nfsbroker
    trigger: true
    passed:
    - security-scan
    - unit-and-integration-test
  - put: nfsbroker
    params:
      merge: true
      repository: nfsbroker

- name: bump-go-module
  serial: true
  plan:
  - in_parallel:
    - get: run-once-a-week
      trigger: true
    - get: source-repo
      resource: nfsbroker-repo
    - get: cryogenics-concourse-tasks
    - get: image-cryogenics-essentials
  - task: bump-go-module
    image: image-cryogenics-essentials
    file: cryogenics-concourse-tasks/deps-automation/bump-go-module/task.yml
    params:
      GIT_USERNAME: *github_user
      GIT_EMAIL: *github_email
  - try:
      load_var: go-module-update-branch
      file: destination-repo/.update-branch-name
      reveal: true
      on_success:
        do:
        - put: nfsbroker-repo-write
          params:
            repository: destination-repo
            branch: &go-module-branch ((.:go-module-update-branch))
        - task: create-pull-request
          image: image-cryogenics-essentials
          file: cryogenics-concourse-tasks/github-automation/create-pr/task.yml
          params:
            GH_TOKEN: *github_access_token
            BASE: *base_branch
            BRANCH: *go-module-branch
            LABELS: dependencies
            TITLE: Bump go module ((.:go-module-update-branch)) in v5.0
            MESSAGE: |
              This is an automatically generated Pull Request from the Cryogenics CI Bot.

              I have detected a new version of a go module and automatically bumped
              it to benefit from the latest changes.

              If this does not look right, please reach out to the mapbu-cryogenics team.
          input_mapping:
            source-repo: nfsbroker-repo-write
