---
#  This pipeline is set automatics, any none committed changes will be lost.
#
# To set the pipeline, run:
#    fly -t cryo-runway set-pipeline -p nfsv3driver -c nfsv3driver.yml
#
# ************************************
# Secrets we need to run this pipeline
# ************************************
#! this needs to come first, else all other vars can't be resolved.
#! cerberus creds are required to access the teams vault instance managed by cerberus. The creds have been created manually via the vault-cli targetting the teams cerberus vault. Example steps to create an approle are here: https://developer.hashicorp.com/vault/docs/auth/approle the required value for policies is `restricted-admin` the auth method is mounted on the standard path.
cerberus: &cerberus
  role_id: ((cerberus-auth.role_id))
  secret_id: ((cerberus-auth.secret_id))
cerberus_url: &cerberus_url ((cerberus-auth.url))

cerberus_secrets:
- &github_ssh_key ((cerberus:github.ssh_key))
- &github_access_token ((cerberus:github.access_token))
# used to get pull requests and get git repos
- &github_user ((cerberus:github.user))
- &github_email ((cerberus:github.email))
#! GitHub email and username are used to sign the commits and PRs for go module auto bumps. Added 2024-02-12

# **************
# End of secrets
# **************
var_sources:
- name: cerberus
  type: vault
  config:
    auth_backend: approle
    auth_params: *cerberus
    url: *cerberus_url
    path_prefix: secret

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/cryogenics/pr-queue-resource

resources:
- name: nfsv3driver-pr
  type: pull-request
  source:
    repository: cloudfoundry/nfsv3driver-pr
    base_branch: master
    disable_forks: true
    access_token: *github_access_token

- name: persi-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git
    branch: master

- name: mapfs
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/mapfs.git
    private_key: *github_ssh_key

- name: docker_driver_integration_tests
  type: git
  source:
    branch: main
    uri: https://github.com/cloudfoundry/docker_driver_integration_tests

- name: image-nfs-unit-tests  
  type: docker-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/cfpersi/nfs-unit-tests
    tag: latest

jobs:
- name: unit-test
  public: true
  plan:
  - get: nfsv3driver-pr
    trigger: true
  - task: build
    file: nfsv3driver-pr/scripts/ci/run_unit.build.yml

- name: security-scan
  plan:
  - in_parallel:
    - get: persi-ci
    - get: image-nfs-unit-tests
    - get: nfsv3driver-pr
      trigger: true
  - task: build
    image: image-nfs-unit-tests
    file: persi-ci/scripts/ci/security-scan.build.yml
    params:
      PATHS: "./"
    input_mapping:
      release-dir: nfsv3driver-pr

- name: integration
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: docker_driver_integration_tests
      - get: nfsv3driver-pr
        passed:
        - unit-test
        trigger: true
      - get: mapfs
  - in_parallel:
      fail_fast: true
      steps:
      - task: run_docker_driver_integration_tests
        file: nfsv3driver-pr/scripts/ci/run_docker_driver_integration_tests.build.yml
        privileged: true
        params:
          TEST_PACKAGE: docker_driver_integration_tests/
      - task: run_docker_driver_lazy_unmount_integration_tests
        file: nfsv3driver-pr/scripts/ci/run_docker_driver_integration_tests.build.yml
        privileged: true
        params:
          TEST_PACKAGE: docker_driver_integration_tests/lazy_unmount
      - task: run_driver_broker_compatibility_tests
        file: nfsv3driver-pr/scripts/ci/run_docker_driver_integration_tests.build.yml
        privileged: true
        params:
          TEST_PACKAGE: docker_driver_integration_tests/compatibility

- name: merge-pr
  serial: true
  plan:
  - get: nfsv3driver-pr
    trigger: true
    passed:
    - security-scan
    - integration
  - put: nfsv3driver-pr
    params:
      merge: true
      repository: nfsv3driver
