resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: cryogenics/pr-queue-resource

resources:
- name: persi-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git
    branch: freezing

- name: existingvolumebroker
  type: git
  source:
    uri: git@github.com:cloudfoundry/existingvolumebroker.git
    branch: master
    private_key: ((github.ssh_key))

- name: goshims
  type: git
  source:
    uri: git@github.com:cloudfoundry/goshims.git
    branch: master
    private_key: ((github.ssh_key))

- name: goshims-version
  type: semver
  source:
    access_key_id: ((aws/goshims-uploader.id))
    bucket: goshims-versions
    initial_version: 0.1.0
    key: current-version
    region_name: us-east-1
    secret_access_key: ((aws/goshims-uploader.secret))

- name: existingvolumebroker-version
  type: semver
  source:
    access_key_id: ((aws/existingvolumebroker-uploader.id))
    bucket: existingvolumebroker-versions
    initial_version: 0.1.0
    key: current-version
    region_name: us-east-1
    secret_access_key: ((aws/existingvolumebroker-uploader.secret))

- name: service-broker-store
  type: git
  source:
    uri: git@github.com:cloudfoundry/service-broker-store.git
    branch: master
    private_key: ((github.ssh_key))

- name: service-broker-store-version
  type: semver
  source:
    access_key_id: ((aws/service-broker-store-uploader.id))
    bucket: service-broker-store-versions
    initial_version: 0.1.0
    key: current-version
    region_name: us-east-1
    secret_access_key: ((aws/service-broker-store-uploader.secret))

- name: volumedriver
  type: git
  source:
    uri: git@github.com:cloudfoundry/volumedriver.git
    branch: master
    private_key: ((github.ssh_key))

- name: volumedriver-version
  type: semver
  source:
    access_key_id: ((aws/volumedriver-uploader.id))
    bucket: volumedriver-versions
    initial_version: 0.1.0
    key: current-version
    region_name: us-east-1
    secret_access_key: ((aws/volumedriver-uploader.secret))

- name: volume-mount-options
  type: git
  source:
    uri: git@github.com:cloudfoundry/volume-mount-options.git
    branch: master
    private_key: ((github.ssh_key))

- name: volume-mount-options-version
  type: semver
  source:
    access_key_id: ((aws/volume-mount-options-uploader.id))
    bucket: volume-mount-options-versions
    initial_version: 0.1.0
    key: current-version
    region_name: us-east-1
    secret_access_key: ((aws/volume-mount-options-uploader.secret))

- name: volumedriver-pr
  type: pull-request
  source:
    uri: cloudfoundry/volumedriver
    base_branch: master
    access_token: ((github.access_token))
    disable_forks: true

jobs:
- name: existingvolumebroker-unit
  public: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: existingvolumebroker
        trigger: true
      - get: existingvolumebroker-version
  - task: existingvolumebroker-unit
    file: persi-ci/scripts/ci/run_unit.build.yml
    input_mapping:
      gomod: existingvolumebroker

- name: bump-minor-existingvolumebroker-version
  serial: true
  plan:
    - get: existingvolumebroker
      trigger: true
      passed:
        - existingvolumebroker-unit
    - get: existingvolumebroker-version
      passed:
        - existingvolumebroker-unit
    - put: existingvolumebroker
      params:
        repository: existingvolumebroker
        tag: existingvolumebroker-version/version
        tag_prefix: "v"
        only_tag: true
    - put: existingvolumebroker-version
      params:
        bump: minor

- name: service-broker-store-unit
  public: true
  plan:
    - in_parallel:
        fail_fast: true
        steps:
          - get: persi-ci
          - get: service-broker-store
            trigger: true
          - get: service-broker-store-version
    - task: service-broker-store-unit
      file: persi-ci/scripts/ci/run_unit.build.yml
      input_mapping:
        gomod: service-broker-store

- name: bump-minor-service-broker-store-version
  serial: true
  plan:
    - get: service-broker-store
      trigger: true
      passed:
        - service-broker-store-unit
    - get: service-broker-store-version
      passed:
        - service-broker-store-unit
    - put: service-broker-store
      params:
        repository: service-broker-store
        tag: service-broker-store-version/version
        tag_prefix: "v"
        only_tag: true
    - put: service-broker-store-version
      params:
        bump: minor

- name: volumedriver-unit
  public: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: volumedriver
        trigger: true
      - get: volumedriver-version
  - task: volumedriver-unit
    file: persi-ci/scripts/ci/run_unit.build.yml
    input_mapping:
      gomod: volumedriver
    params:
      NODES: 1

- name: bump-minor-volumedriver-version
  serial: true
  plan:
    - get: volumedriver
      trigger: true
      passed:
        - volumedriver-unit
    - get: volumedriver-version
      passed:
        - volumedriver-unit
    - put: volumedriver
      params:
        repository: volumedriver
        tag: volumedriver-version/version
        tag_prefix: "v"
        only_tag: true
    - put: volumedriver-version
      params:
        bump: minor

- name: volume-mount-options-unit
  public: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: volume-mount-options
        trigger: true
      - get: volume-mount-options-version
  - task: volume-mount-options-unit
    file: persi-ci/scripts/ci/run_unit.build.yml
    input_mapping:
      gomod: volume-mount-options

- name: bump-minor-volume-mount-options-version
  serial: true
  plan:
    - get: volume-mount-options
      trigger: true
      passed:
        - volume-mount-options-unit
    - get: volume-mount-options-version
      passed:
        - volume-mount-options-unit
    - put: volume-mount-options
      params:
        repository: volume-mount-options
        tag: volume-mount-options-version/version
        tag_prefix: "v"
        only_tag: true
    - put: volume-mount-options-version
      params:
        bump: minor

- name: goshims-build
  public: true
  plan:
    - in_parallel:
        fail_fast: true
        steps:
          - get: persi-ci
          - get: goshims
            trigger: true
          - get: goshims-version
    - task: build
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: golang
            tag: latest
        inputs:
          - name: goshims
        run:
          path: bash
          args:
            - -exc
            - |
              cd goshims
              go build ./...

- name: bump-minor-goshims-version
  serial: true
  plan:
    - get: goshims
      trigger: true
      passed:
        - goshims-build
    - get: goshims-version
      passed:
        - goshims-build
    - put: goshims
      params:
        repository: goshims
        tag: goshims-version/version
        tag_prefix: "v"
        only_tag: true
    - put: goshims-version
      params:
        bump: minor

- name: volumedriver-merge-pr
  plan:
  - get: volumedriver-pr
    trigger: true
  - put: volumedriver-pr
    params:
      merge: true
      repository: volumedriver-pr
