---
#  This pipeline is set automatically, any non-committed changes will be lost.
#
# To set the pipeline, run:
#    fly -t cryo-runway set-pipeline -p shared-units -c shared-units.yml
#
# ************************************
# Secrets we need to run this pipeline
# ************************************
#! this needs to come first, else all other vars can't be resolved.
#! cerberus creds are required to access the teams vault instance managed by cerberus. The creds have been created
#! manually via the vault-cli targeting the teams cerberus vault. Example steps to create an approle are here:
#! https://developer.hashicorp.com/vault/docs/auth/approle the required value for policies is `restricted-admin` the
#! auth method is mounted on the standard path.
cerberus: &cerberus
  role_id: ((cerberus-auth.role_id))
  secret_id: ((cerberus-auth.secret_id))
cerberus_url: &cerberus_url ((cerberus-auth.url))

cerberus_secrets:
- &github_ssh_key ((cerberus:github.ssh_key))
- &github_access_token ((cerberus:github.access_token))
# SSH key/access token is used for accessing the GH release and PRs
- &github_user ((cerberus:github.user))
- &github_email ((cerberus:github.email))
#! GitHub email and username are used to sign the commits and PRs for go module auto bumps. Added 2024-02-19

- &goshims_uploader_role_id ((cerberus:aws/volume-services/goshims-uploader.role_id))
- &goshims_uploader_role_secret ((cerberus:aws/volume-services/goshims-uploader.role_secret))
- &goshims_uploader_role_arn ((cerberus:aws/volume-services/goshims-uploader.role_arn))
# Used to get a semver of goshims

- &existingvolumebroker_uploader_role_id ((cerberus:aws/volume-services/existingvolumebroker-uploader.role_id))
- &existingvolumebroker_uploader_role_secret ((cerberus:aws/volume-services/existingvolumebroker-uploader.role_secret))
- &existingvolumebroker_uploader_role_arn ((cerberus:aws/volume-services/existingvolumebroker-uploader.role_arn))
# Used to get a semver of existingvolumebroker

- &service_broker_store_uploader_role_id ((cerberus:aws/volume-services/service-broker-store-uploader.role_id))
- &service_broker_store_uploader_role_secret ((cerberus:aws/volume-services/service-broker-store-uploader.role_secret))
- &service_broker_store_uploader_role_arn ((cerberus:aws/volume-services/service-broker-store-uploader.role_arn))
# Used to get a semver of service_broker_store_uploader

- &volumedriver_uploader_role_id ((cerberus:aws/volume-services/volumedriver-uploader.role_id))
- &volumedriver_uploader_role_secret ((cerberus:aws/volume-services/volumedriver-uploader.role_secret))
- &volumedriver_uploader_role_arn ((cerberus:aws/volume-services/volumedriver-uploader.role_arn))
# Used to get a semver of volumedriver_uploader

- &volume_mount_options_uploader_role_id ((cerberus:aws/volume-services/volume-mount-options-uploader.role_id))
- &volume_mount_options_uploader_role_secret ((cerberus:aws/volume-services/volume-mount-options-uploader.role_secret))
- &volume_mount_options_uploader_role_arn ((cerberus:aws/volume-services/volume-mount-options-uploader.role_arn))
# Used to get a semver of volume_mount_options_uploader

# **************
# End of secrets
# **************
var_sources:
- name: cerberus
  type: vault
  config:
    auth_backend: approle
    auth_params: *cerberus
    url: *cerberus_url
    path_prefix: secret

groups:
- name: auto-tagging
  jobs:
  - '*-version'
  - '*-gate'
- name: merge-prs
  jobs:
  - '*-build'
  - '*-unit'
  - '*-merge-pr'
- name: updates
  jobs:
  - 'bump-go-module-*'

resource_types:
- name: semver
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/concourse/semver-resource
    tag: 1.6
  type: docker-image

- name: pull-request
  type: docker-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/cryogenics/pr-queue-resource

resources:
- name: every-monday
  type: time
  icon: timer-outline
  source:
    days: [Monday]

- name: persi-ci
  type: git
  icon: github
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git
    branch: master

- name: existingvolumebroker
  type: git
  icon: github
  source:
    uri: git@github.com:cloudfoundry/existingvolumebroker.git
    branch: master
    private_key: *github_ssh_key

- name: existingvolumebroker-write
  type: git
  icon: git
  source:
    uri: git@github.com:cloudfoundry/existingvolumebroker.git
    private_key: *github_ssh_key
    commit_filter:
      exclude:
      - ;resource comment; This resource is used exclusively for pushing new changes

- name: goshims
  type: git
  icon: github
  source:
    uri: git@github.com:cloudfoundry/goshims.git
    branch: master
    private_key: *github_ssh_key

- name: goshims-version
  type: semver
  icon: counter
  source:
    access_key_id: *goshims_uploader_role_id
    bucket: goshims-versions
    initial_version: 0.1.0
    key: current-version
    region_name: us-east-1
    secret_access_key: *goshims_uploader_role_secret
    assume_role_arn: *goshims_uploader_role_arn

- name: existingvolumebroker-version
  type: semver
  icon: counter
  source:
    access_key_id: *existingvolumebroker_uploader_role_id
    bucket: existingvolumebroker-versions
    initial_version: 0.1.0
    key: current-version
    region_name: us-east-1
    secret_access_key: *existingvolumebroker_uploader_role_secret
    assume_role_arn: *existingvolumebroker_uploader_role_arn

- name: service-broker-store
  type: git
  icon: github
  source:
    uri: git@github.com:cloudfoundry/service-broker-store.git
    branch: master
    private_key: *github_ssh_key

- name: service-broker-store-version
  type: semver
  icon: counter
  source:
    access_key_id: *service_broker_store_uploader_role_id
    bucket: service-broker-store-versions
    initial_version: 0.1.0
    key: current-version
    region_name: us-east-1
    secret_access_key: *service_broker_store_uploader_role_secret
    assume_role_arn: *service_broker_store_uploader_role_arn

- name: volumedriver
  type: git
  icon: github
  source:
    uri: git@github.com:cloudfoundry/volumedriver.git
    branch: master
    private_key: *github_ssh_key

- name: volumedriver-write
  type: git
  icon: git
  source:
    uri: git@github.com:cloudfoundry/volumedriver.git
    private_key: *github_ssh_key
    commit_filter:
      exclude:
      - ;resource comment; This resource is used exclusively for pushing new changes

- name: volumedriver-version
  type: semver
  icon: counter
  source:
    access_key_id: *volumedriver_uploader_role_id
    bucket: volumedriver-versions
    initial_version: 0.1.0
    key: current-version
    region_name: us-east-1
    secret_access_key: *volumedriver_uploader_role_secret
    assume_role_arn: *volumedriver_uploader_role_arn

- name: volume-mount-options
  type: git
  icon: github
  source:
    uri: git@github.com:cloudfoundry/volume-mount-options.git
    branch: master
    private_key: *github_ssh_key

- name: volume-mount-options-version
  type: semver
  icon: counter
  source:
    access_key_id: *volume_mount_options_uploader_role_id
    bucket: volume-mount-options-versions
    initial_version: 0.1.0
    key: current-version
    region_name: us-east-1
    secret_access_key: *volume_mount_options_uploader_role_secret
    assume_role_arn: *volume_mount_options_uploader_role_arn

- name: volumedriver-pr
  type: pull-request
  icon: source-pull
  source:
    repository: cloudfoundry/volumedriver
    base_branch: master
    access_token: *github_access_token
    disable_forks: true

- name: goshims-pr
  type: pull-request
  icon: source-pull
  source:
    repository: cloudfoundry/goshims
    base_branch: master
    access_token: *github_access_token
    disable_forks: true

- name: existingvolumebroker-pr
  type: pull-request
  icon: source-pull
  source:
    repository: cloudfoundry/existingvolumebroker
    base_branch: master
    access_token: *github_access_token
    disable_forks: true

- name: service-broker-store-pr
  type: pull-request
  icon: source-pull
  source:
    repository: cloudfoundry/service-broker-store
    base_branch: master
    access_token: *github_access_token
    disable_forks: true

- name: volume-mount-options-pr
  type: pull-request
  icon: source-pull
  source:
    repository: cloudfoundry/volume-mount-options
    base_branch: master
    access_token: *github_access_token
    disable_forks: true

- name: image-golang
  type: registry-image
  icon: docker
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/golang
    tag: latest

- name: image-cryogenics-essentials
  type: registry-image
  icon: docker
  source:
    repository: harbor-repo.vmware.com/cryogenics/essentials
    tag: latest

- name: cryogenics-concourse-tasks
  type: git
  icon: github
  source:
    uri: git@github.com:pivotal/cryogenics-concourse-tasks.git
    branch: main
    private_key: *github_ssh_key

jobs:
- name: existingvolumebroker-unit
  public: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: image-golang
      - get: existingvolumebroker
        resource: existingvolumebroker-pr
        trigger: true
  - task: existingvolumebroker-unit
    image: image-golang
    file: persi-ci/scripts/ci/run_unit_ginkgo_v2.build.yml
    input_mapping:
      gomod: existingvolumebroker

- name: bump-existingvolumebroker-gate
  serial: true
  plan:
  - get: every-monday
    trigger: true
  - get: existingvolumebroker

- name: bump-minor-existingvolumebroker-version
  serial: true
  plan:
  - get: existingvolumebroker
    passed: [bump-existingvolumebroker-gate]
    trigger: true
  - get: existingvolumebroker-version
  - put: existingvolumebroker
    params:
      repository: existingvolumebroker
      tag: existingvolumebroker-version/version
      tag_prefix: "v"
      only_tag: true
  - put: existingvolumebroker-version
    params:
      bump: minor

- name: bump-go-module
  plan:
  - in_parallel:
    - get: source-repo
      resource: existingvolumebroker
    - get: cryogenics-concourse-tasks
    - get: image-cryogenics-essentials
    - get: every-monday
      trigger: true
  - task: bump-go-module
    file: cryogenics-concourse-tasks/deps-automation/bump-go-module/task.yml
    image: image-cryogenics-essentials
    params:
      GIT_USERNAME: *github_user
      GIT_EMAIL: *github_email
      ROOT_DIRECTORIES: .
  - try:
      load_var: go-module-update-branch
      file: destination-repo/.update-branch-name
      on_success:
        do:
        - put: existingvolumebroker-write
          params:
            repository: destination-repo
            branch: &go-module-branch ((.:go-module-update-branch))
        - task: create-go-module-bump-pull-request
          file: cryogenics-concourse-tasks/github-automation/create-pr/task.yml
          image: image-cryogenics-essentials
          params:
            BASE: master
            BRANCH: *go-module-branch
            LABELS: dependencies
            TITLE: Bump go module ((.:go-module-update-branch))
            MESSAGE: |
              This is an automatically generated Pull Request from the Cryogenics CI Bot.

              I have detected a new version of a go module and automatically bumped
              it to benefit from the latest changes.

              If this does not look right, please reach out to the [#mapbu-cryogenics](https://vmware.slack.com/archives/C01DXEYRKRU) team.
          input_mapping:
            source-repo: existingvolumebroker-write


- name: service-broker-store-unit
  public: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: image-golang
      - get: service-broker-store
        resource: service-broker-store-pr
        trigger: true
  - task: service-broker-store-unit
    image: image-golang
    file: persi-ci/scripts/ci/run_unit_ginkgo_v2.build.yml
    input_mapping:
      gomod: service-broker-store

- name: bump-service-broker-store-gate
  serial: true
  plan:
  - get: every-monday
    trigger: true
  - get: service-broker-store

- name: bump-minor-service-broker-store-version
  serial: true
  plan:
  - get: service-broker-store
    passed: [bump-service-broker-store-gate]
    trigger: true
  - get: service-broker-store-version
  - put: service-broker-store
    params:
      repository: service-broker-store
      tag: service-broker-store-version/version
      tag_prefix: "v"
      only_tag: true
  - put: service-broker-store-version
    params:
      bump: minor

- name: volumedriver-unit
  public: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: image-golang
      - get: volumedriver
        resource: volumedriver-pr
        trigger: true
  - task: volumedriver-unit
    image: image-golang
    file: persi-ci/scripts/ci/run_unit_ginkgo_v2.build.yml
    input_mapping:
      gomod: volumedriver
    params:
      NODES: 1

- name: bump-volumedriver-gate
  serial: true
  plan:
  - get: every-monday
    trigger: true
  - get: volumedriver

- name: bump-minor-volumedriver-version
  serial: true
  plan:
  - get: volumedriver
    passed: [bump-volumedriver-gate]
    trigger: true
  - get: volumedriver-version
  - put: volumedriver
    params:
      repository: volumedriver
      tag: volumedriver-version/version
      tag_prefix: "v"
      only_tag: true
  - put: volumedriver-version
    params:
      bump: minor

- name: bump-go-module-volumedriver
  plan:
  - in_parallel:
    - get: source-repo
      resource: volumedriver
    - get: cryogenics-concourse-tasks
    - get: image-cryogenics-essentials
    - get: every-monday
      trigger: true
  - task: bump-go-module
    file: cryogenics-concourse-tasks/deps-automation/bump-go-module/task.yml
    image: image-cryogenics-essentials
    params:
      GIT_USERNAME: *github_user
      GIT_EMAIL: *github_email
      ROOT_DIRECTORIES: .
  - try:
      load_var: go-module-update-branch
      file: destination-repo/.update-branch-name
      on_success:
        do:
        - put: volumedriver-write
          params:
            repository: destination-repo
            branch: &go-module-branch ((.:go-module-update-branch))
        - task: create-go-module-bump-pull-request
          file: cryogenics-concourse-tasks/github-automation/create-pr/task.yml
          image: image-cryogenics-essentials
          params:
            BASE: master
            BRANCH: *go-module-branch
            LABELS: dependencies
            TITLE: Bump go module ((.:go-module-update-branch))
            MESSAGE: |
              This is an automatically generated Pull Request from the Cryogenics CI Bot.

              I have detected a new version of a go module and automatically bumped
              it to benefit from the latest changes.

              If this does not look right, please reach out to the [#mapbu-cryogenics](https://vmware.slack.com/archives/C01DXEYRKRU) team.
          input_mapping:
            source-repo: volumedriver-write

- name: volume-mount-options-unit
  public: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: image-golang
      - get: volume-mount-options
        resource: volume-mount-options-pr
        trigger: true
  - task: volume-mount-options-unit
    image: image-golang
    file: persi-ci/scripts/ci/run_unit_ginkgo_v2.build.yml
    input_mapping:
      gomod: volume-mount-options

- name: bump-volume-mount-options-gate
  serial: true
  plan:
  - get: every-monday
    trigger: true
  - get: volume-mount-options

- name: bump-minor-volume-mount-options-version
  serial: true
  plan:
  - get: volume-mount-options
    passed: [bump-volume-mount-options-gate]
    trigger: true
  - get: volume-mount-options-version
  - put: volume-mount-options
    params:
      repository: volume-mount-options
      tag: volume-mount-options-version/version
      tag_prefix: "v"
      only_tag: true
  - put: volume-mount-options-version
    params:
      bump: minor

- name: goshims-build
  public: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: image-golang
      - get: goshims
        resource: goshims-pr
        trigger: true
  - task: build
    image: image-golang
    config:
      platform: linux
      inputs:
      - name: goshims
      run:
        path: bash
        args:
        - -exc
        - |
          cd goshims
          go build ./...

- name: bump-goshims-gate
  serial: true
  plan:
  - get: every-monday
    trigger: true
  - get: goshims

- name: bump-minor-goshims-version
  serial: true
  plan:
  - get: goshims
    passed: [bump-goshims-gate]
    trigger: true
  - get: goshims-version
  - put: goshims
    params:
      repository: goshims
      tag: goshims-version/version
      tag_prefix: "v"
      only_tag: true
  - put: goshims-version
    params:
      bump: minor

- name: volumedriver-merge-pr
  plan:
  - get: volumedriver-pr
    passed:
    - volumedriver-unit
    trigger: true
  - put: volumedriver-pr
    params:
      merge: true
      repository: volumedriver-pr

- name: goshims-merge-pr
  plan:
  - get: goshims-pr
    passed:
    - goshims-build
    trigger: true
  - put: goshims-pr
    params:
      merge: true
      repository: goshims-pr

- name: existingvolumebroker-merge-pr
  plan:
  - get: existingvolumebroker-pr
    passed:
    - existingvolumebroker-unit
    trigger: true
  - put: existingvolumebroker-pr
    params:
      merge: true
      repository: existingvolumebroker-pr

- name: service-broker-store-merge-pr
  plan:
  - get: service-broker-store-pr
    passed:
    - service-broker-store-unit
    trigger: true
  - put: service-broker-store-pr
    params:
      merge: true
      repository: service-broker-store-pr

- name: volume-mount-options-merge-pr
  plan:
  - get: volume-mount-options-pr
    passed:
    - volume-mount-options-unit
    trigger: true
  - put: volume-mount-options-pr
    params:
      merge: true
      repository: volume-mount-options-pr
