---
groups:
- name: auto-tagging
  jobs:
  - '*-version'
  - '*-gate'
- name: merge-prs
  jobs:
  - '*-build'
  - '*-unit'
  - '*-merge-pr'

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: cryogenics/pr-queue-resource

resources:
- name: every-monday
  type: time
  source:
    days: [Monday]

- name: persi-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git
    branch: master

- name: existingvolumebroker
  type: git
  source:
    uri: git@github.com:cloudfoundry/existingvolumebroker.git
    branch: master
    private_key: ((github.ssh_key))

- name: goshims
  type: git
  source:
    uri: git@github.com:cloudfoundry/goshims.git
    branch: master
    private_key: ((github.ssh_key))

- name: goshims-version
  type: semver
  source:
    access_key_id: ((aws/goshims-uploader.role_id))
    bucket: goshims-versions
    initial_version: 0.1.0
    key: current-version
    region_name: us-east-1
    secret_access_key: ((aws/goshims-uploader.role_secret))
    assume_role_arn: ((aws/goshims-uploader.role_arn))

- name: existingvolumebroker-version
  type: semver
  source:
    access_key_id: ((aws/existingvolumebroker-uploader.role_id))
    bucket: existingvolumebroker-versions
    initial_version: 0.1.0
    key: current-version
    region_name: us-east-1
    secret_access_key: ((aws/existingvolumebroker-uploader.role_secret))
    assume_role_arn: ((aws/existingvolumebroker-uploader.role_arn))

- name: service-broker-store
  type: git
  source:
    uri: git@github.com:cloudfoundry/service-broker-store.git
    branch: master
    private_key: ((github.ssh_key))

- name: service-broker-store-version
  type: semver
  source:
    access_key_id: ((aws/service-broker-store-uploader.role_id))
    bucket: service-broker-store-versions
    initial_version: 0.1.0
    key: current-version
    region_name: us-east-1
    secret_access_key: ((aws/service-broker-store-uploader.role_secret))
    assume_role_arn: ((aws/service-broker-store-uploader.role_arn))

- name: volumedriver
  type: git
  source:
    uri: git@github.com:cloudfoundry/volumedriver.git
    branch: master
    private_key: ((github.ssh_key))

- name: volumedriver-version
  type: semver
  source:
    access_key_id: ((aws/volumedriver-uploader.role_id))
    bucket: volumedriver-versions
    initial_version: 0.1.0
    key: current-version
    region_name: us-east-1
    secret_access_key: ((aws/volumedriver-uploader.role_secret))
    assume_role_arn: ((aws/volumedriver-uploader.role_arn))

- name: volume-mount-options
  type: git
  source:
    uri: git@github.com:cloudfoundry/volume-mount-options.git
    branch: master
    private_key: ((github.ssh_key))

- name: volume-mount-options-version
  type: semver
  source:
    access_key_id: ((aws/volume-mount-options-uploader.role_id))
    bucket: volume-mount-options-versions
    initial_version: 0.1.0
    key: current-version
    region_name: us-east-1
    secret_access_key: ((aws/volume-mount-options-uploader.role_secret))
    assume_role_arn: ((aws/volume-mount-options-uploader.role_arn))

- name: volumedriver-pr
  type: pull-request
  source:
    repository: cloudfoundry/volumedriver
    base_branch: master
    access_token: ((github.access_token))
    disable_forks: true

- name: goshims-pr
  type: pull-request
  source:
    repository: cloudfoundry/goshims
    base_branch: master
    access_token: ((github.access_token))
    disable_forks: true

- name: existingvolumebroker-pr
  type: pull-request
  source:
    repository: cloudfoundry/existingvolumebroker
    base_branch: master
    access_token: ((github.access_token))
    disable_forks: true

- name: service-broker-store-pr
  type: pull-request
  source:
    repository: cloudfoundry/service-broker-store
    base_branch: master
    access_token: ((github.access_token))
    disable_forks: true

- name: volume-mount-options-pr
  type: pull-request
  source:
    repository: cloudfoundry/volume-mount-options
    base_branch: master
    access_token: ((github.access_token))
    disable_forks: true

jobs:
- name: existingvolumebroker-unit
  public: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: existingvolumebroker
        resource: existingvolumebroker-pr
        trigger: true
  - task: existingvolumebroker-unit
    file: persi-ci/scripts/ci/run_unit_ginkgo_v2.build.yml
    input_mapping:
      gomod: existingvolumebroker

- name: bump-existingvolumebroker-gate
  serial: true
  plan:
  - get: every-monday
    trigger: true
  - get: existingvolumebroker

- name: bump-minor-existingvolumebroker-version
  serial: true
  plan:
  - get: existingvolumebroker
    passed: [bump-existingvolumebroker-gate]
    trigger: true
  - get: existingvolumebroker-version
  - put: existingvolumebroker
    params:
      repository: existingvolumebroker
      tag: existingvolumebroker-version/version
      tag_prefix: "v"
      only_tag: true
  - put: existingvolumebroker-version
    params:
      bump: minor

- name: service-broker-store-unit
  public: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: service-broker-store
        resource: service-broker-store-pr
        trigger: true
  - task: service-broker-store-unit
    file: persi-ci/scripts/ci/run_unit_ginkgo_v2.build.yml
    input_mapping:
      gomod: service-broker-store

- name: bump-service-broker-store-gate
  serial: true
  plan:
  - get: every-monday
    trigger: true
  - get: service-broker-store

- name: bump-minor-service-broker-store-version
  serial: true
  plan:
  - get: service-broker-store
    passed: [bump-service-broker-store-gate]
    trigger: true
  - get: service-broker-store-version
  - put: service-broker-store
    params:
      repository: service-broker-store
      tag: service-broker-store-version/version
      tag_prefix: "v"
      only_tag: true
  - put: service-broker-store-version
    params:
      bump: minor

- name: volumedriver-unit
  public: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: volumedriver
        resource: volumedriver-pr
        trigger: true
  - task: volumedriver-unit
    file: persi-ci/scripts/ci/run_unit_ginkgo_v2.build.yml
    input_mapping:
      gomod: volumedriver
    params:
      NODES: 1

- name: bump-volumedriver-gate
  serial: true
  plan:
  - get: every-monday
    trigger: true
  - get: volumedriver

- name: bump-minor-volumedriver-version
  serial: true
  plan:
  - get: volumedriver
    passed: [bump-volumedriver-gate]
    trigger: true
  - get: volumedriver-version
  - put: volumedriver
    params:
      repository: volumedriver
      tag: volumedriver-version/version
      tag_prefix: "v"
      only_tag: true
  - put: volumedriver-version
    params:
      bump: minor

- name: volume-mount-options-unit
  public: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: volume-mount-options
        resource: volume-mount-options-pr
        trigger: true
  - task: volume-mount-options-unit
    file: persi-ci/scripts/ci/run_unit_ginkgo_v2.build.yml
    input_mapping:
      gomod: volume-mount-options

- name: bump-volume-mount-options-gate
  serial: true
  plan:
  - get: every-monday
    trigger: true
  - get: volume-mount-options

- name: bump-minor-volume-mount-options-version
  serial: true
  plan:
  - get: volume-mount-options
    passed: [bump-volume-mount-options-gate]
    trigger: true
  - get: volume-mount-options-version
  - put: volume-mount-options
    params:
      repository: volume-mount-options
      tag: volume-mount-options-version/version
      tag_prefix: "v"
      only_tag: true
  - put: volume-mount-options-version
    params:
      bump: minor

- name: goshims-build
  public: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: goshims
        resource: goshims-pr
        trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: latest
      inputs:
      - name: goshims
      run:
        path: bash
        args:
        - -exc
        - |
          cd goshims
          go build ./...

- name: bump-goshims-gate
  serial: true
  plan:
  - get: every-monday
    trigger: true
  - get: goshims

- name: bump-minor-goshims-version
  serial: true
  plan:
  - get: goshims
    passed: [bump-goshims-gate]
    trigger: true
  - get: goshims-version
  - put: goshims
    params:
      repository: goshims
      tag: goshims-version/version
      tag_prefix: "v"
      only_tag: true
  - put: goshims-version
    params:
      bump: minor

- name: volumedriver-merge-pr
  plan:
  - get: volumedriver-pr
    passed:
    - volumedriver-unit
    trigger: true
  - put: volumedriver-pr
    params:
      merge: true
      repository: volumedriver-pr

- name: goshims-merge-pr
  plan:
  - get: goshims-pr
    passed:
    - goshims-build
    trigger: true
  - put: goshims-pr
    params:
      merge: true
      repository: goshims-pr

- name: existingvolumebroker-merge-pr
  plan:
  - get: existingvolumebroker-pr
    passed:
    - existingvolumebroker-unit
    trigger: true
  - put: existingvolumebroker-pr
    params:
      merge: true
      repository: existingvolumebroker-pr

- name: service-broker-store-merge-pr
  plan:
  - get: service-broker-store-pr
    passed:
    - service-broker-store-unit
    trigger: true
  - put: service-broker-store-pr
    params:
      merge: true
      repository: service-broker-store-pr

- name: volume-mount-options-merge-pr
  plan:
  - get: volume-mount-options-pr
    passed:
    - volume-mount-options-unit
    trigger: true
  - put: volume-mount-options-pr
    params:
      merge: true
      repository: volume-mount-options-pr
