resources:
- name: persi-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git

- name: existingvolumebroker
  type: git
  source:
    uri: git@github.com:cloudfoundry/existingvolumebroker.git
    branch: master
    private_key: {{existingvolumebroker-github-deploy-key}}

- name: existingvolumebroker-version
  type: semver
  source:
    access_key_id: {{existingvolumebroker-uploader_aws_ID}}
    bucket: existingvolumebroker-versions
    initial_version: 0.1.0
    key: current-version
    region_name: us-east-1
    secret_access_key: {{existingvolumebroker-uploader_aws_secret}}

- name: volumedriver
  type: git
  source:
    uri: git@github.com:cloudfoundry/volumedriver.git
    branch: master
    private_key: {{volumedriver-github-deploy-key}}

- name: volumedriver-version
  type: semver
  source:
    access_key_id: {{volumedriver-uploader_aws_ID}}
    bucket: volumedriver-versions
    initial_version: 0.1.0
    key: current-version
    region_name: us-east-1
    secret_access_key: {{volumedriver-uploader_aws_secret}}

- name: volume-mount-options
  type: git
  source:
    uri: git@github.com:cloudfoundry/volume-mount-options.git
    branch: master
    private_key: {{volume-mount-options--github-deploy-key}}

- name: volume-mount-options-version
  type: semver
  source:
    access_key_id: {{volume-mount-options-uploader_aws_ID}}
    bucket: volume-mount-options-versions
    initial_version: 0.1.0
    key: current-version
    region_name: us-east-1
    secret_access_key: {{volume-mount-options-uploader_aws_secret}}

jobs:
- name: existingvolumebroker-unit
  public: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: existingvolumebroker
        trigger: true
      - get: existingvolumebroker-version
  - task: existingvolumebroker-unit
    file: persi-ci/scripts/ci/run_unit.build.yml
    input_mapping:
      gomod: existingvolumebroker

- name: bump-minor-existingvolumebroker-version
  serial: true
  plan:
    - get: existingvolumebroker
      trigger: true
      passed:
        - existingvolumebroker-unit
    - get: existingvolumebroker-version
      passed:
        - existingvolumebroker-unit
    - put: existingvolumebroker
      params:
        repository: existingvolumebroker
        tag: existingvolumebroker-version/version
        tag_prefix: "v"
        only_tag: true
    - put: existingvolumebroker-version
      params:
        bump: minor

- name: volumedriver-unit
  public: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: volumedriver
        trigger: true
      - get: volumedriver-version
  - task: volumedriver-unit
    file: persi-ci/scripts/ci/run_unit.build.yml
    input_mapping:
      gomod: volumedriver
    params:
      NODES: 1

- name: bump-minor-volumedriver-version
  serial: true
  plan:
    - get: volumedriver
      trigger: true
      passed:
        - volumedriver-unit
    - get: volumedriver-version
      passed:
        - volumedriver-unit
    - put: volumedriver
      params:
        repository: volumedriver
        tag: volumedriver-version/version
        tag_prefix: "v"
        only_tag: true
    - put: volumedriver-version
      params:
        bump: minor

- name: volume-mount-options-unit
  public: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: volume-mount-options
        trigger: true
      - get: volume-mount-options-version
  - task: volume-mount-options-unit
    file: persi-ci/scripts/ci/run_unit.build.yml
    input_mapping:
      gomod: volume-mount-options

- name: bump-minor-volume-mount-options-version
  serial: true
  plan:
    - get: volume-mount-options
      trigger: true
      passed:
        - volume-mount-options-unit
    - get: volume-mount-options-version
      passed:
        - volume-mount-options-unit
    - put: volume-mount-options
      params:
        repository: volume-mount-options
        tag: volume-mount-options-version/version
        tag_prefix: "v"
        only_tag: true
    - put: volume-mount-options-version
      params:
        bump: minor


