resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: cryogenics/pr-queue-resource

resources:
- name: smbdriver
  type: pull-request
  source:
    repository: cloudfoundry/smbdriver
    base_branch: master
    disable_forks: true
    access_token: ((github.access_token))

- name: persi-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git
    branch: master

- name: docker_driver_integration_tests
  type: git
  source:
    branch: main
    uri: https://github.com/cloudfoundry/docker_driver_integration_tests

jobs:
- name: unit-test
  public: true
  plan:
  - get: smbdriver
    trigger: true
  - task: build
    file: smbdriver/scripts/ci/run_unit.build.yml

- name: security-scan
  plan:
    - in_parallel:
        - get: persi-ci
        - get: smbdriver
          trigger: true
    - task: build
      file: persi-ci/scripts/ci/security-scan.build.yml
      params:
        PATHS: "./"
      input_mapping:
        release-dir: smbdriver

- name: integration
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: docker_driver_integration_tests
      - get: smbdriver
        passed:
        - unit-test
        trigger: true
  - in_parallel:
      fail_fast: true
      steps:
      - task: run_docker_driver_integration_tests
        file: smbdriver/scripts/ci/run_docker_driver_integration_tests.build.yml
        privileged: true
        tags: [ os_ubuntu ]
        params:
          TEST_PACKAGE: docker_driver_integration_tests/
      - task: run_docker_driver_lazy_unmount_integration_tests
        file: smbdriver/scripts/ci/run_docker_driver_integration_tests.build.yml
        privileged: true
        tags: [ os_ubuntu ]
        params:
          TEST_PACKAGE: docker_driver_integration_tests/lazy_unmount
      - task: run_driver_broker_compatibility_tests
        file: smbdriver/scripts/ci/run_docker_driver_integration_tests.build.yml
        privileged: true
        tags: [ os_ubuntu ]
        params:
          TEST_PACKAGE: docker_driver_integration_tests/compatibility

- name: merge-pr
  plan:
  - get: smbdriver
    trigger: true
    passed:
    - security-scan
    - integration
  - put: smbdriver
    params:
      merge: true
      repository: smbdriver
