resource_types:
  - name: go-mod-vendor-tidy-git
    type: docker-image
    source:
      repository: cfpersi/fork-git-resource
      tag: latest

resources:
- name: smbdriver
  type: go-mod-vendor-tidy-git
  source:
    uri: git@github.com:cloudfoundry/smbdriver.git
    private_key: ((github.ssh_key))

- name: smb-volume-release
  type: git
  source:
    branch: master
    private_key: ((github.ssh_key))
    uri: git@github.com:cloudfoundry/smb-volume-release.git

- name: persi-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git
    branch: freezing

- name: docker_driver_integration_tests
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/docker_driver_integration_tests

jobs:
- name: unit-test
  public: true
  plan:
  - get: smbdriver
    trigger: true
  - task: build
    file: smbdriver/scripts/ci/run_unit.build.yml

- name: security-scan
  plan:
    - in_parallel:
        - get: persi-ci
        - get: smbdriver
          trigger: true
    - task: build
      file: persi-ci/scripts/ci/security-scan.build.yml
      params:
        PATHS: "./"
      input_mapping:
        release-dir: smbdriver

- name: integration
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: docker_driver_integration_tests
      - get: smbdriver
        passed:
        - unit-test
        trigger: true
  - in_parallel:
      fail_fast: true
      steps:
      - task: run_docker_driver_integration_tests
        file: smbdriver/scripts/ci/run_docker_driver_integration_tests.build.yml
        privileged: true
        tags: [ os_ubuntu ]
        params:
          TEST_PACKAGE: docker_driver_integration_tests/
      - task: run_docker_driver_lazy_unmount_integration_tests
        file: smbdriver/scripts/ci/run_docker_driver_integration_tests.build.yml
        privileged: true
        tags: [ os_ubuntu ]
        params:
          TEST_PACKAGE: docker_driver_integration_tests/lazy_unmount
      - task: run_driver_broker_compatibility_tests
        file: smbdriver/scripts/ci/run_docker_driver_integration_tests.build.yml
        privileged: true
        tags: [ os_ubuntu ]
        params:
          TEST_PACKAGE: docker_driver_integration_tests/compatibility

- name: release-job-tests
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: smb-volume-release
      - get: smbdriver
        passed:
        - integration
        - security-scan
        trigger: true
  - task: bump-submodule
    file: persi-ci/scripts/ci/bump_submodule.build.yml
    input_mapping:
      release-repo: smb-volume-release
      submodule-repo: smbdriver
    params:
      SUBMODULE_PATH: src/code.cloudfoundry.org/smbdriver
  - task: bosh-release-test
    attempts: 3
    input_mapping:
      smb-volume-release: bumped-repo
      smb-volume-release-concourse-tasks: bumped-repo
    file: smb-volume-release/scripts/ci/run_bosh_release_tests.build.yml
    privileged: true
  - put: smb-volume-release
    params:
      repository: bumped-repo
      rebase: true
