resources:
- name: smbbroker
  type: git
  source:
    uri: git@github.com:cloudfoundry/smbbroker.git
    private_key: ((github.ssh_key))

- name: persi-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git
    branch: freezing

jobs:
- name: unit-test
  public: true
  plan:
  - get: smbbroker
    trigger: true
  - task: build
    file: smbbroker/scripts/ci/run_unit.build.yml

- name: security-scan
  plan:
    - in_parallel:
        - get: persi-ci
        - get: smbbroker
          trigger: true
    - task: build
      file: persi-ci/scripts/ci/security-scan.build.yml
      params:
        PATHS: "./"
      input_mapping:
        release-dir: smbbroker
