---
#!  WARNING: this pipeline is automatically set and manual changes will go away.
#!
#!  To set pipeline manually run:
#!    fly -t cryo set-pipeline -p smbbroker -c smbbroker.yml

# ************************************
# Secrets we need to run this pipeline
# ************************************

cerberus_secrets:
#! GitHub SSH Key is used to push git commits and accessing repositories. Added 2024-02-19
- &github_access_token ((github-tas-runtime-bot/access-token))
- &github_ssh_key ((github-tas-runtime-bot/private-key))

#! GitHub email and username are used to sign the commits and PRs for go module auto bumps. Added 2024-02-19
- &github_user App Platform Runtime Working Group CI Bot
- &github_email tas-runtime.pdl+tas-runtime-bot@broadcom.com

- &gcr_viewer_key  ((gcp-tas-runtime-service-account/config-json))

# **************
# End of secrets
# **************

groups:
- name: test
  jobs:
  - unit-test
  - security-scan
  - merge-pr
- name: updates
  jobs:
  - bump-go-module


resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: us-west2-docker.pkg.dev/mapbu-cryogenics/concourse-resources/pr-queue-resource
    username: _json_key
    password: *gcr_viewer_key

resources:
- name: smbbroker
  type: pull-request
  icon: source-pull
  source:
    repository: cloudfoundry/smbbroker
    base_branch: master
    disable_forks: true
    access_token: *github_access_token

- name: git-smbbroker
  type: git
  icon: github
  source:
    uri: git@github.com:cloudfoundry/smbbroker.git
    private_key: *github_ssh_key
    branch: master

- name: git-smbbroker-write
  type: git
  icon: git
  source:
    uri: git@github.com:cloudfoundry/smbbroker.git
    private_key: *github_ssh_key
    commit_filter:
      exclude:
      - ;resource comment; This resource is used exclusively for pushing new changes

- name: persi-ci
  type: git
  icon: github
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git
    branch: master

- name: image-cryogenics-essentials
  type: registry-image
  icon: docker
  source:
    repository: us-west2-docker.pkg.dev/mapbu-cryogenics/essentials/cryo-essentials
    username: _json_key
    password: *gcr_viewer_key
    
- name: cryogenics-concourse-tasks
  type: git
  icon: github
  source:
    uri: git@github.com:pivotal/cryogenics-concourse-tasks.git
    branch: main
    private_key: ((tas-runtime-bot-cryo-deploy-key-for-pivotal-org/private_key))

- name: run-once-a-week
  type: time
  icon: clock-outline
  source:
    days: [ Wednesday ]

jobs:
- name: unit-test
  public: true
  plan:
  - get: smbbroker
    trigger: true
  - get: image-cryogenics-essentials
  - task: build
    image: image-cryogenics-essentials
    file: smbbroker/scripts/ci/run_unit.build.yml

- name: security-scan
  plan:
  - in_parallel:
    - get: image-cryogenics-essentials
    - get: persi-ci
    - get: smbbroker
      trigger: true
  - task: build
    image: image-cryogenics-essentials
    file: persi-ci/scripts/ci/security-scan.build.yml
    params:
      PATHS: "./"
    input_mapping:
      release-dir: smbbroker

- name: merge-pr
  plan:
  - get: smbbroker
    trigger: true
    passed:
    - security-scan
    - unit-test
  - put: smbbroker
    params:
      merge: true
      repository: smbbroker

- name: bump-go-module
  plan:
  - in_parallel:
    - get: source-repo
      resource: git-smbbroker
    - get: cryogenics-concourse-tasks
    - get: image-cryogenics-essentials
    - get: run-once-a-week
      trigger: true
  - task: bump-go-module
    image: image-cryogenics-essentials
    file: cryogenics-concourse-tasks/deps-automation/bump-go-module/task.yml
    params:
      GIT_USERNAME: *github_user
      GIT_EMAIL: *github_email
      ROOT_DIRECTORIES: .
  - try:
      load_var: go-module-update-branch
      file: destination-repo/.update-branch-name
      on_success:
        do:
        - put: git-smbbroker-write
          params:
            repository: destination-repo
            branch: &go-module-branch ((.:go-module-update-branch))
        - task: create-go-module-bump-pull-request
          image: image-cryogenics-essentials
          file: cryogenics-concourse-tasks/github-automation/create-pr/task.yml
          params:
            GH_TOKEN: *github_access_token
            BASE: master
            BRANCH: *go-module-branch
            LABELS: dependencies
            TITLE: Bump go module ((.:go-module-update-branch))
            MESSAGE: |
              This is an automatically generated Pull Request from the Cryogenics CI Bot.

              I have detected a new version of a go module and automatically bumped
              it to benefit from the latest changes.

              If this does not look right, please reach out to the mapbu-cryogenics team.
          input_mapping:
            source-repo: git-smbbroker-write
