---
#!  WARNING: this pipeline is automatically set and manual changes will go away.
#!
#!  To set pipeline manually run:
#!    fly set-pipeline -p smbbroker -c smbbroker.yml

# ************************************
# Secrets we need to run this pipeline
# ************************************

#! this needs to come first, else all other vars can't be resolved.
#! cerberus creds are required to access the teams vault instance managed by cerberus. The creds have been created
#! manually via the vault-cli targeting the teams cerberus vault. Example steps to create an approle are here:
#! https://developer.hashicorp.com/vault/docs/auth/approle the required value for policies is `restricted-admin`
#! the auth method is mounted on the standard path.
cerberus: &cerberus
  role_id: ((cerberus-auth.role_id))
  secret_id: ((cerberus-auth.secret_id))
cerberus_url: &cerberus_url ((cerberus-auth.url))

cerberus_secrets:
- &github_access_token ((cerberus:github.access_token))
- &github_ssh_key ((cerberus:github.ssh_key))
#! GitHub SSH Key is used to push git commits and accessing repositories. Added 2024-02-19
- &github_user ((cerberus:github.user))
- &github_email ((cerberus:github.email))
#! GitHub email and username are used to sign the commits and PRs for go module auto bumps. Added 2024-02-19

# **************
# End of secrets
# **************

var_sources:
- name: cerberus
  type: vault
  config:
    auth_backend: approle
    auth_params: *cerberus
    url: *cerberus_url
    path_prefix: secret

groups:
- name: test
  jobs:
  - unit-test
  - security-scan
  - merge-pr
- name: updates
  jobs:
  - bump-go-module


resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: harbor-repo.vmware.com/cryogenics/pr-queue-resource

resources:
- name: smbbroker
  type: pull-request
  icon: source-pull
  source:
    repository: cloudfoundry/smbbroker
    base_branch: master
    disable_forks: true
    access_token: *github_access_token

- name: git-smbbroker
  type: git
  icon: github
  source:
    uri: git@github.com:cloudfoundry/smbbroker.git
    private_key: *github_ssh_key
    branch: master

- name: git-smbbroker-write
  type: git
  icon: git
  source:
    uri: git@github.com:cloudfoundry/smbbroker.git
    private_key: *github_ssh_key
    commit_filter:
      exclude:
      - ;resource comment; This resource is used exclusively for pushing new changes

- name: persi-ci
  type: git
  icon: github
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git
    branch: master

- name: image-nfs-unit-tests
  type: docker-image
  icon: docker
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/cfpersi/nfs-unit-tests
    tag: latest

- name: image-cryogenics-essentials
  type: docker-image
  icon: docker
  source:
    repository: harbor-repo.vmware.com/cryogenics/essentials
    tag: latest
    
- name: image-golang
  type: registry-image
  icon: docker
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/golang
    tag: latest

- name: cryogenics-concourse-tasks
  type: git
  icon: github
  source:
    uri: git@github.com:pivotal/cryogenics-concourse-tasks.git
    private_key: *github_ssh_key
    branch: main

- name: run-once-a-week
  type: time
  icon: clock-outline
  source:
    days: [ Monday ]

jobs:
- name: unit-test
  public: true
  plan:
  - get: smbbroker
    trigger: true
  - get: image-golang
  - task: build
    image: image-golang
    file: smbbroker/scripts/ci/run_unit.build.yml

- name: security-scan
  plan:
  - in_parallel:
    - get: image-nfs-unit-tests
    - get: persi-ci
    - get: smbbroker
      trigger: true
  - task: build
    image: image-nfs-unit-tests
    file: persi-ci/scripts/ci/security-scan.build.yml
    params:
      PATHS: "./"
    input_mapping:
      release-dir: smbbroker

- name: merge-pr
  plan:
  - get: smbbroker
    trigger: true
    passed:
    - security-scan
    - unit-test
  - put: smbbroker
    params:
      merge: true
      repository: smbbroker

- name: bump-go-module
  plan:
  - in_parallel:
    - get: source-repo
      resource: git-smbbroker
    - get: cryogenics-concourse-tasks
    - get: image-cryogenics-essentials
    - get: run-once-a-week
      trigger: true
  - task: bump-go-module
    file: cryogenics-concourse-tasks/deps-automation/bump-go-module/task.yml
    image: image-cryogenics-essentials
    params:
      GIT_USERNAME: *github_user
      GIT_EMAIL: *github_email
      ROOT_DIRECTORIES: .
  - try:
      load_var: go-module-update-branch
      file: destination-repo/.update-branch-name
      on_success:
        do:
        - put: git-smbbroker-write
          params:
            repository: destination-repo
            branch: &go-module-branch ((.:go-module-update-branch))
        - task: create-go-module-bump-pull-request
          file: cryogenics-concourse-tasks/github-automation/create-pr/task.yml
          image: image-cryogenics-essentials
          params:
            BASE: master
            BRANCH: *go-module-branch
            LABELS: dependencies
            TITLE: Bump go module ((.:go-module-update-branch))
            MESSAGE: |
              This is an automatically generated Pull Request from the Cryogenics CI Bot.

              I have detected a new version of a go module and automatically bumped
              it to benefit from the latest changes.

              If this does not look right, please reach out to the [#mapbu-cryogenics](https://vmware.slack.com/archives/C01DXEYRKRU) team.
          input_mapping:
            source-repo: git-smbbroker-write
