---
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: cryogenics/pr-queue-resource

resources:
- name: smbbroker
  type: pull-request
  source:
    repository: cloudfoundry/smbbroker
    base_branch: master
    disable_forks: true
    access_token: ((github.access_token))

- name: persi-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git
    branch: master

jobs:
- name: unit-test
  public: true
  plan:
  - get: smbbroker
    trigger: true
  - task: build
    file: smbbroker/scripts/ci/run_unit.build.yml

- name: security-scan
  plan:
  - in_parallel:
    - get: persi-ci
    - get: smbbroker
      trigger: true
  - task: build
    file: persi-ci/scripts/ci/security-scan.build.yml
    params:
      PATHS: "./"
    input_mapping:
      release-dir: smbbroker

- name: merge-pr
  plan:
  - get: smbbroker
    trigger: true
    passed:
    - security-scan
    - unit-test
  - put: smbbroker
    params:
      merge: true
      repository: smbbroker
