---
#!  WARNING: this pipeline is automatically set and manual changes will go away.
#!
#!  To set pipeline manually run:
#!    fly -t cryo set-pipeline -p smbdriver -c smbdriver.yml

#! ************************************
#! Secrets we need to run this pipeline
#! ************************************

cerberus_secrets:
#! GitHub SSH Key is used to push git commits and accessing repositories. Added 2024-02-19
- &github_access_token ((github-tas-runtime-bot/access-token))
- &github_ssh_key ((github-tas-runtime-bot/private-key))

#! GitHub email and username are used to sign the commits and PRs for go module auto bumps. Added 2024-02-19
- &github_user App Platform Runtime Working Group CI Bot
- &github_email tas-runtime.pdl+tas-runtime-bot@broadcom.com

- &gcr_viewer_key  ((gcp-tas-runtime-service-account/config-json))

#! **************
#! End of secrets
#! **************


groups:
- name: test
  jobs:
  - unit-test
  - security-scan
  - integration
  - merge-pr
- name: updates
  jobs:
  - bump-go-module

resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: us-west2-docker.pkg.dev/mapbu-cryogenics/concourse-resources/pr-queue-resource
    username: _json_key
    password: *gcr_viewer_key

resources:
- name: smbdriver
  type: pull-request
  icon: source-pull
  source:
    repository: cloudfoundry/smbdriver
    base_branch: master
    disable_forks: true
    access_token: *github_access_token

- name: git-smbdriver
  type: git
  icon: github
  source:
    uri: git@github.com:cloudfoundry/smbdriver.git
    private_key: *github_ssh_key
    branch: master

- name: git-smbdriver-write
  type: git
  icon: git
  source:
    uri: git@github.com:cloudfoundry/smbdriver.git
    private_key: *github_ssh_key
    commit_filter:
      exclude:
      - ;resource comment; This resource is used exclusively for pushing new changes

- name: persi-ci
  type: git
  icon: github
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git
    branch: master

- name: docker_driver_integration_tests
  type: git
  icon: github
  source:
    branch: main
    uri: https://github.com/cloudfoundry/docker_driver_integration_tests

- name: cryogenics-concourse-tasks
  type: git
  icon: github
  source:
    uri: git@github.com:pivotal/cryogenics-concourse-tasks.git
    branch: main
    private_key: ((tas-runtime-bot-cryo-deploy-key-for-pivotal-org/private_key))

- name: image-bosh
  type: registry-image
  icon: docker
  source:
    repository: us-west2-docker.pkg.dev/mapbu-cryogenics/dockerhub-proxy-cache/bosh/docker-cpi
    username: _json_key
    password: *gcr_viewer_key
    tag: latest

- name: docker_image_samba_input
  type: registry-image
  icon: docker
  source:
    repository: us-west2-docker.pkg.dev/mapbu-cryogenics/dockerhub-proxy-cache/dperson/samba
    username: _json_key
    password: *gcr_viewer_key
    tag: latest

- name: image-cryogenics-essentials
  type: registry-image
  icon: docker
  source:
    repository: us-west2-docker.pkg.dev/mapbu-cryogenics/essentials/cryo-essentials
    username: _json_key
    password: *gcr_viewer_key

- name: run-once-a-week
  type: time
  icon: clock-outline
  source:
    days: [ Wednesday ]

jobs:
- name: unit-test
  public: true
  plan:
  - in_parallel:
    - get: smbdriver
      trigger: true
    - get: image-cryogenics-essentials
  - task: build
    image: image-cryogenics-essentials
    file: smbdriver/scripts/ci/run_unit.build.yml

- name: security-scan
  plan:
  - in_parallel:
    - get: image-cryogenics-essentials
    - get: persi-ci
    - get: smbdriver
      trigger: true
  - task: build
    image: image-cryogenics-essentials
    file: persi-ci/scripts/ci/security-scan.build.yml
    params:
      PATHS: "./"
    input_mapping:
      release-dir: smbdriver

- name: integration
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: docker_driver_integration_tests
      - get: smbdriver
        passed:
        - unit-test
        trigger: true
      - get: image-bosh
      - get: docker_image_samba_input
        params:
          format: oci
  - in_parallel:
      fail_fast: true
      steps:
      - task: run_docker_driver_integration_tests
        image: image-bosh
        file: smbdriver/scripts/ci/run_docker_driver_integration_tests.build.yml
        privileged: true
        params:
          TEST_PACKAGE: docker_driver_integration_tests/
      - task: run_docker_driver_lazy_unmount_integration_tests
        image: image-bosh
        file: smbdriver/scripts/ci/run_docker_driver_integration_tests.build.yml
        privileged: true
        params:
          TEST_PACKAGE: docker_driver_integration_tests/lazy_unmount
      - task: run_driver_broker_compatibility_tests
        image: image-bosh
        file: smbdriver/scripts/ci/run_docker_driver_integration_tests.build.yml
        privileged: true
        params:
          TEST_PACKAGE: docker_driver_integration_tests/compatibility

- name: merge-pr
  plan:
  - get: smbdriver
    trigger: true
    passed:
    - security-scan
    - integration
  - put: smbdriver
    params:
      merge: true
      repository: smbdriver

- name: bump-go-module
  plan:
  - in_parallel:
    - get: source-repo
      resource: git-smbdriver
    - get: cryogenics-concourse-tasks
    - get: image-cryogenics-essentials
    - get: run-once-a-week
      trigger: true
  - task: bump-go-module
    image: image-cryogenics-essentials
    file: cryogenics-concourse-tasks/deps-automation/bump-go-module/task.yml
    params:
      GIT_USERNAME: *github_user
      GIT_EMAIL: *github_email
      ROOT_DIRECTORIES: .
  - try:
      load_var: go-module-update-branch
      file: destination-repo/.update-branch-name
      on_success:
        do:
        - put: git-smbdriver-write
          params:
            repository: destination-repo
            branch: &go-module-branch ((.:go-module-update-branch))
        - task: create-go-module-bump-pull-request
          image: image-cryogenics-essentials
          file: cryogenics-concourse-tasks/github-automation/create-pr/task.yml
          params:
            BASE: master
            BRANCH: *go-module-branch
            LABELS: dependencies
            TITLE: Bump go module ((.:go-module-update-branch))
            MESSAGE: |
              This is an automatically generated Pull Request from the Cryogenics CI Bot.

              I have detected a new version of a go module and automatically bumped
              it to benefit from the latest changes.

              If this does not look right, please reach out to the mapbu-cryogenics team.
          input_mapping:
            source-repo: git-smbdriver-write
