---
#!  WARNING: this pipeline is automatically set and manual changes will go away.
#!
#!  To set pipeline manually run:
#!    fly set-pipeline -p smbdriver -c smbdriver.yml

# ************************************
# Secrets we need to run this pipeline
# ************************************

#! this needs to come first, else all other vars can't be resolved.
#! cerberus creds are required to access the teams vault instance managed by cerberus. The creds have been created manually via the vault-cli targetting the teams cerberus vault. Example steps to create an approle are here: https://developer.hashicorp.com/vault/docs/auth/approle the required value for policies is `restricted-admin` the auth method is mounted on the standard path.
cerberus: &cerberus
  role_id: ((cerberus-auth.role_id))
  secret_id: ((cerberus-auth.secret_id))
cerberus_url: &cerberus_url ((cerberus-auth.url))

github_access_token: &github_access_token ((cerberus:github.access_token))

# **************
# End of secrets
# **************

var_sources:
- name: cerberus
  type: vault
  config:
    auth_backend: approle
    auth_params: *cerberus
    url: *cerberus_url
    path_prefix: secret


resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: harbor-repo.vmware.com/cryogenics/pr-queue-resource

resources:
- name: smbdriver
  type: pull-request
  source:
    repository: cloudfoundry/smbdriver
    base_branch: master
    disable_forks: true
    access_token: *github_access_token

- name: persi-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/persi-ci.git
    branch: master

- name: docker_driver_integration_tests
  type: git
  source:
    branch: main
    uri: https://github.com/cloudfoundry/docker_driver_integration_tests

- name: image-nfs-unit-tests
  type: docker-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/cfpersi/nfs-unit-tests
    tag: latest

- name: image-golang
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/golang
    tag: latest

- name: image-bosh
  type: docker-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/bosh/docker-cpi
    privileged: true
    tag: latest

jobs:
- name: unit-test
  public: true
  plan:
  - in_parallel:
    - get: smbdriver
      trigger: true
    - get: image-golang
  - task: build
    image: image-golang
    file: smbdriver/scripts/ci/run_unit.build.yml

- name: security-scan
  plan:
  - in_parallel:
    - get: image-nfs-unit-tests
    - get: persi-ci
    - get: smbdriver
      trigger: true
  - task: build
    image: image-nfs-unit-tests
    file: persi-ci/scripts/ci/security-scan.build.yml
    params:
      PATHS: "./"
    input_mapping:
      release-dir: smbdriver

- name: integration
  serial: true
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: persi-ci
      - get: docker_driver_integration_tests
      - get: smbdriver
        passed:
        - unit-test
        trigger: true
      - get: image-bosh
  - in_parallel:
      fail_fast: true
      steps:
      - task: run_docker_driver_integration_tests
        image: image-bosh
        file: smbdriver/scripts/ci/run_docker_driver_integration_tests.build.yml
        privileged: true
        params:
          TEST_PACKAGE: docker_driver_integration_tests/
      - task: run_docker_driver_lazy_unmount_integration_tests
        image: image-bosh
        file: smbdriver/scripts/ci/run_docker_driver_integration_tests.build.yml
        privileged: true
        params:
          TEST_PACKAGE: docker_driver_integration_tests/lazy_unmount
      - task: run_driver_broker_compatibility_tests
        image: image-bosh
        file: smbdriver/scripts/ci/run_docker_driver_integration_tests.build.yml
        privileged: true
        params:
          TEST_PACKAGE: docker_driver_integration_tests/compatibility

- name: merge-pr
  plan:
  - get: smbdriver
    trigger: true
    passed:
    - security-scan
    - integration
  - put: smbdriver
    params:
      merge: true
      repository: smbdriver
