resources:
- name: smith-env
  type: pcf-pool
  source:
    api_token: ((persi_toolsmiths_env_api_token))
    hostname: environments.toolsmiths.cf-app.com
    pool_name: cf-deployment
  tags: [ toolsmiths-shared-vsphere ]

- name: persi-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/persi-ci
    branch: master

- name: nfs-volume-release-tarball
  type: s3
  source:
    access_key_id: {{nfsvolume-uploader_aws_ID}}
    bucket: nfs-volume-release-tarballs
    regexp: nfs-volume-(.*).tgz
    secret_access_key: {{nfsvolume-uploader_aws_secret}}

- name: nfsvolume-version
  type: semver
  source:
    access_key_id: {{nfsvolume-uploader_aws_ID}}
    bucket: nfsvolume-release-versions
    initial_version: 0.0.0
    key: current-version
    region_name: us-east-1
    secret_access_key: {{nfsvolume-uploader_aws_secret}}

- name: nfs-volume-release
  type: git
  source:
    branch: master
    username: {{github-user}}
    password: {{github-password}}
    uri: https://github.com/cloudfoundry/nfs-volume-release.git
    ignore_paths:
    - scripts

- name: smb-volume-release
  type: git
  source:
    branch: master
    username: {{github-user}}
    password: {{github-password}}
    uri: https://github.com/cloudfoundry/smb-volume-release.git

- name: smb-volume-version
  type: semver
  source:
    access_key_id: {{smbvolume-uploader_aws_ID}}
    bucket: smb-volume-release-versions
    initial_version: 0.0.0
    key: current-version
    region_name: us-east-1
    secret_access_key: {{smbvolume-uploader_aws_secret}}

- name: smb-volume-release-tarball
  type: s3
  source:
    bucket: smb-volume-release-tarballs
    regexp: smb-volume-(.*).tgz
    access_key_id: {{smbvolume-uploader_aws_ID}}
    secret_access_key: {{smbvolume-uploader_aws_secret}}

- name: mapfs-release-tarball
  type: s3
  source:
    access_key_id: {{mapfs-uploader_aws_ID}}
    bucket: mapfs-release-tarballs
    regexp: mapfs-(.*).tgz
    secret_access_key: {{mapfs-uploader_aws_secret}}

- name: mapfs-version
  type: semver
  source:
    access_key_id: {{mapfs-uploader_aws_ID}}
    bucket: mapfs-versions
    initial_version: 0.0.0
    key: current-version
    region_name: us-east-1
    secret_access_key: {{mapfs-uploader_aws_secret}}

- name: mapfs-release
  type: git
  source:
    branch: master
    username: {{github-user}}
    password: {{github-password}}
    uri: https://github.com/cloudfoundry/mapfs-release.git

- name: cf-deployment
  type: git
  source:
    branch: release-candidate
    uri: https://github.com/cloudfoundry/cf-deployment.git

- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git

- name: cf-volume-services-acceptance-tests
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-volume-services-acceptance-tests.git

resource_types:
- name: pcf-pool
  type: docker-image
  source:
    repository: cftoolsmiths/toolsmiths-envs-resource

jobs:
- name: claim-env
  plan:
  - get: persi-ci
  - put: smith-env
    params:
      action: claim
    tags: [ toolsmiths-shared-vsphere ]
  - task: output-env-details
    file: persi-ci/scripts/ci/claim-pooled-env.build.yml
    input_mapping:
      pooled-env: smith-env

- name: unclaim-env
  plan:
    - get: smith-env
      tags: [ toolsmiths-shared-vsphere ]
    - put: smith-env
      params:
        action: unclaim
        env_file: smith-env/metadata
      tags: [ toolsmiths-shared-vsphere ]

- name: deploy-cf
  public: true
  build_logs_to_retain: 100
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: smith-env
        tags: [ toolsmiths-shared-vsphere ]
        passed: [ claim-env ]
        trigger: true
      - get: cf-deployment-concourse-tasks
      - get: cf-deployment
      - get: persi-ci
      - get: nfs-volume-release
      - get: nfs-volume-release-tarball
      - get: nfsvolume-version
      - get: mapfs-release
      - get: mapfs-release-tarball
      - get: mapfs-version
      - get: smb-volume-release
      - get: smb-volume-release-tarball
      - get: smb-volume-version
  - task: collect-tarballs
    file: persi-ci/scripts/ci/collect-tarballs.build.yml
    params: {}
    input_mapping:
      persi-ci: persi-ci
      nfs-tarball: nfs-volume-release-tarball
      mapfs-tarball: mapfs-release-tarball
      smb-tarball: smb-volume-release-tarball
      nfs-version: nfsvolume-version
      mapfs-version: mapfs-version
      smb-version: smb-volume-version
  - task: collect-persi-ci-ops-files
    file: cf-deployment-concourse-tasks/collect-ops-files/task.yml
    input_mapping:
      base-ops-files: cf-deployment
      new-ops-files: persi-ci
    params:
      BASE_OPS_FILE_DIR: "operations"
      NEW_OPS_FILES: "operations/scale-up-routers-and-cells.yml
                      operations/enable-nfs-test-server-two.yml
                      operations/enable-smb-test-server-two.yml"
  - task: collect-tarball-ops-files
    file: cf-deployment-concourse-tasks/collect-ops-files/task.yml
    input_mapping:
      base-ops-files: collected-ops-files
      new-ops-files: collected-tarballs
    params:
      BASE_OPS_FILE_DIR: "operations"
      NEW_OPS_FILES: "operations/update-releases.yml"
  - task: add-tarballs
    file: cf-deployment-concourse-tasks/collect-ops-files/task.yml
    input_mapping:
      base-ops-files: collected-ops-files
      new-ops-files: collected-tarballs
    params:
      BASE_OPS_FILE_DIR: "."
      NEW_OPS_FILES: "nfs.tgz
                      mapfs.tgz
                      smb.tgz"
  - task: generate-variables
    file: persi-ci/scripts/ci/generate_variables.build.yml
    params:
      # BBL_IAAS: gcp
      GENERATE_DATADOG_VARS: false
      GENERATE_NFS_VARS: true
      GENERATE_SMB_VARS: true
      GENERATE_GCS_BLOBSTORE_VARS: false
      SMB_USERNAME: {{smb_pats_username_two}}
      SMB_PASSWORD: {{smb_pats_password_two}}
  - task: bosh-deploy-cf
    file: persi-ci/scripts/ci/deploy-smith-cf-d.build.yml
    input_mapping:
      toolsmiths-env: smith-env
      cf-deployment: cf-deployment
      ops-files: collected-ops-files
      vars-files: generated-vars
    params:
      VARS_FILES: "nfs-vars.yml smb-vars.yml"
      OPS_FILES: "operations/use-compiled-releases.yml
                  operations/scale-to-one-az.yml
                  operations/scale-up-routers-and-cells.yml
                  operations/enable-nfs-volume-service.yml
                  operations/enable-nfs-test-server-two.yml
                  operations/test/enable-nfs-test-server.yml
                  operations/test/enable-smb-test-server.yml
                  operations/backup-and-restore/enable-backup-restore.yml
                  operations/backup-and-restore/enable-restore-nfs-broker.yml
                  operations/enable-smb-volume-service.yml
                  operations/enable-smb-test-server-two.yml
                  operations/update-releases.yml"
  - task: enable-docker
    attempts: 2
    file: persi-ci/scripts/ci/set-feature-flags.build.yml
    input_mapping:
      toolsmiths-env: smith-env
    params:
      ENABLED_FEATURE_FLAGS: |
        diego_docker
  - task: run-smoke-tests
    file: cf-deployment-concourse-tasks/run-errand/task.yml
    input_mapping:
      toolsmiths-env: smith-env
    params:
      ERRAND_NAME: smoke_tests

- name: deploy-nfs-smb-brokers
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: cf-deployment-concourse-tasks
      - get: smith-env
        tags: [ toolsmiths-shared-vsphere ]
        passed: [ deploy-cf ]
        trigger: true
  - task: run-nfs-broker-errand
    file: cf-deployment-concourse-tasks/run-errand/task.yml
    input_mapping:
      toolsmiths-env: smith-env
    params:
      ERRAND_NAME: nfsbrokerpush
  - task: run-smb-broker-errand
    file: cf-deployment-concourse-tasks/run-errand/task.yml
    input_mapping:
      toolsmiths-env: smith-env
    params:
      ERRAND_NAME: smbbrokerpush

- name: pats-nfs
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: cf-volume-services-acceptance-tests
      - get: persi-ci
      - get: smith-env
        tags: [ toolsmiths-shared-vsphere ]
        passed: [ deploy-nfs-smb-brokers ]
        trigger: true
  - task: generate-pats-config
    file: persi-ci/scripts/ci/generate_pats_config.build.yml
    params:
      CF_USERNAME: admin
      BIND_BOGUS_CONFIG: '{"uid":"1000","gid":"1000"}'
      BIND_CONFIG: '["{\"uid\":\"1000\",\"gid\":\"1000\"}", "{\"uid\":\"1000\",\"gid\":\"1000\",\"mount\": \"/var/vcap/data/foo\"}", "{\"uid\":\"1000\",\"gid\":\"1000\", \"version\": \"3.0\"}", "{\"uid\":\"1000\",\"gid\":\"1000\",\"version\": \"3.0\",\"mount\": \"/var/vcap/data/foo\"}", "{\"uid\":\"1000\",\"gid\":\"1000\", \"version\": \"4.1\"}", "{\"uid\":\"1000\",\"gid\":\"1000\",\"version\": \"4.1\",\"mount\": \"/var/vcap/data/foo\"}", "{\"uid\":\"1000\",\"gid\":\"1000\", \"version\": \"4.2\"}", "{\"uid\":\"1000\",\"gid\":\"1000\",\"version\": \"4.2\",\"mount\": \"/var/vcap/data/foo\"}"]'
      CREATE_BOGUS_CONFIG: '{"share":"nfstestserver.service.cf.internal/export/nonexistensevol"}'
      CREATE_CONFIG: '{"share":"nfstestserver.service.cf.internal/export/users"}'
      PLAN_NAME: Existing
      SERVICE_NAME: nfs
  - task: run-pats
    file: persi-ci/scripts/ci/run-pats.build.yml
    input_mapping:
      director-state: bbl-state
    attempts: 3
    params:
      PARALLEL_NODES: 2
      TEST_MOUNT_FAIL_LOGGING: true
      TEST_MOUNT_OPTIONS: true
      TEST_MULTI_CELL: true
      TEST_READ_ONLY: true
