#!/bin/bash
set -eux

source cf-deployment-concourse-tasks/shared-functions
source persi-ci/efs/shared-functions

if [ "$USE_VARS_STORE" == true ]; then
  trap "commit_vars_store ${PWD}" EXIT
fi

setup_bosh_env_vars_with_ssh
SYSTEM_DOMAIN=${BOSH_ENVIRONMENT}.sslip.io

check_input_params
if [ "$REGENERATE_VARS_STORE" == true ]; then
    remove_vars_store
fi

bosh_interpolate
bosh_deploy
teardown_bosh_env_vars
