#!/bin/bash -eux

function setup_bosh_env_vars_with_ssh() {
  set +x
  source cf-deployment-concourse-tasks/bosh-lite-aws/setenv.sh
  ssh -4 -D 5000 -fNC jumpbox@$BOSH_ENVIRONMENT -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i cf-deployment-concourse-tasks/bosh-lite-aws/jumpbox.key &
  set -x
}

function teardown_bosh_env_vars() {
  pkill ssh || true
}
