#!/bin/bash
set -eux

mkdir -p cf-deployment-concourse-tasks-patched
cp -rp cf-deployment-concourse-tasks/* cf-deployment-concourse-tasks-patched/

cp persi-ci/efs/shared-functions cf-deployment-concourse-tasks-patched/shared-functions

mkdir -p cf-deployment-concourse-tasks-patched/bosh-lite-aws
cp -rp deployments-persi/persi-ci/deployments/bosh-lite-aws/* cf-deployment-concourse-tasks-patched/bosh-lite-aws/
chmod 600 cf-deployment-concourse-tasks-patched/bosh-lite-aws/jumpbox.key

printf "\n\nteardown_bosh_env_vars" >> cf-deployment-concourse-tasks-patched/bosh-upload-stemcell-from-cf-deployment/task
printf "\n\nteardown_bosh_env_vars" >> cf-deployment-concourse-tasks-patched/bosh-deploy/task
