#!/bin/bash -eu

function main() {
  cp -pr "bbl-config/plan-patches/openvpn-aws" merged-plan-patch

  mkdir -p merged-plan-patch/openvpn-aws/vars
  cat <<EOT > merged-plan-patch/openvpn-aws/vars/zone.tfvars
availability_zones=["us-west-2a", "us-west-2b", "us-west-2c"]
EOT
}

main
