#!/bin/bash -eu

mkdir -p bosh-env

set +x
if [ -d smith-env ]; then
  eval "$(bbl print-env --metadata-file smith-env/metadata)"
  touch bosh-env/set-env.sh
else
  if [ -d director-state ]; then
    bbl --state-dir director-state/${BBL_STATE_DIR} print-env > bosh-env/set-env.sh
    bbl --state-dir director-state/${BBL_STATE_DIR} ssh-key > bosh-env/ssh-key
    bbl --state-dir director-state/${BBL_STATE_DIR} director-ca-cert > bosh-env/ca-cert.pem
  else
    echo "Must provide either toolsmiths-env or bbl-state as an input"
    exit 1
  fi
fi
set -x

