#!/bin/bash -eu

mkdir -p bosh-env
bbl --state-dir director-state/bbl-state print-env > bosh-env/set-env.sh
bbl --state-dir director-state/bbl-state ssh-key > bosh-env/ssh-key
bbl --state-dir director-state/bbl-state director-ca-cert > bosh-env/ca-cert.pem

