#!/bin/bash -eu

source bosh-env/set-env.sh

export CA_CERT="$PWD/bosh-env/ca-cert.pem"
export BBR_PRIVATE_KEY=$(cat bosh-env/ssh-key)

pushd backup-artifact
  ../binary/bbr deployment --target "${BOSH_ENVIRONMENT}" \
  --username "${BOSH_CLIENT}" \
  --deployment "${DEPLOYMENT_NAME}" \
  pre-backup-check

  ../binary/bbr deployment --target "${BOSH_ENVIRONMENT}" \
  --username "${BOSH_CLIENT}" \
  --deployment "${DEPLOYMENT_NAME}" \
  backup --with-manifest

  cat "${DEPLOYMENT_TIMESTAMP}"
  ls
  mkdir backup
  mv "${DEPLOYMENT_TIMESTAMP}"/* backup/*
  tar -cvf backup.tar -- *
popd

