#!/bin/bash -eu

source bosh-env/set-env.sh

export CA_CERT="$PWD/bosh-env/ca-cert.pem"
export BBR_PRIVATE_KEY=$(cat bosh-env/ssh-key)

pushd backup-artifact
  cat "${DEPLOYMENT_TIMESTAMP}"
  mkdir backup
  tar -C backup -xvf backup.tar
  ../binary/bbr deployment --target "${BOSH_ENVIRONMENT}" \
  --username "${BOSH_CLIENT}" \
  --deployment "${DEPLOYMENT_NAME}" \
  restore \
    --artifact-path backup/"${DEPLOYMENT_TIMESTAMP}"
popd

