#!/bin/bash -eux

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

function shrink_cf_manifest() {
  SMALL_INTERPOLATED_MANIFEST="${INTERPOLATED_MANIFEST}-small"

  apt-get install -y python3-pip
  pip3 install yq

  shrinkcf/shrink.sh -m "${INTERPOLATED_MANIFEST}" -o "${SMALL_INTERPOLATED_MANIFEST}"
  mv "${SMALL_INTERPOLATED_MANIFEST}" "${INTERPOLATED_MANIFEST}"
}

function main() {
  check_input_params
  setup_bosh_env_vars
  bosh_interpolate
  shrink_cf_manifest

  if [ "$REGENERATE_CREDENTIALS" == true ]; then
    remove_credentials_from_credhub
  fi

  bosh_update_dns_runtime_config
  # shellcheck disable=SC2086
  bosh_deploy ${BOSH_DEPLOY_ARGS}
}

main
