#!/bin/bash -eux

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

function shrink_cf_manifest() {
  shrinkcf/shrink.sh -m "${MANIFEST_FILE}" -o "${SMALL_MANIFEST_FILE}"
  mv "${SMALL_MANIFEST_FILE}" "${MANIFEST_FILE}"
}

function main() {
  check_input_params
  setup_bosh_env_vars
  bosh_interpolate
  shrink_cf_manifest

  if [ "$REGENERATE_CREDENTIALS" == true ]; then
    remove_credentials_from_credhub
  fi

  bosh_update_dns_runtime_config
  # shellcheck disable=SC2086
  bosh_deploy ${BOSH_DEPLOY_ARGS}
}

main
