#!/bin/bash

cp -r bosh-release/. bosh-release-updated
REPO_ROOT=bosh-release-updated

source "task-repo/deps-automation/shared/functions.sh"
setup_private_blobstore_config_S3 "$AWS_ACCESS_KEY_ID" "$AWS_SECRET_ACCESS_KEY" "$AWS_ROLE_ARN"
set -eux
cd bosh-release-updated
git checkout -b "$GIT_BRANCH"

current_filename=$(bosh blobs | grep $BLOB_NAME | awk '{print $1}')
current_version=$(echo "$current_filename" | sed -r 's/^.+-([0-9.]+)\.'"$BLOB_EXTENSTION"'.*/\1/')
new_filename=$(ls ../distributed-package | grep -v version)
new_version=$(cat ../distributed-package/version)
if [[ "${current_version}" == "${new_version}" ]]; then
  echo "Versions already match. Skipping update."
  exit 0
fi

echo "updating ${BLOB_NAME} blob from ${current_version} to ${new_version}"
bosh remove-blob "$current_filename"
bosh add-blob "../distributed-package/${new_filename}" "$new_filename"
bosh upload-blobs

git add config/blobs.yml
git config user.name "${GIT_USERNAME}"
git config user.email "${GIT_EMAIL}"
git commit -m "Bump ${BLOB_NAME} from ${current_version} to ${new_version}"