#!/bin/bash

set -e -x -u
source $(pwd)/persi-ci/scripts/ci/utils.sh
check_param SUBMODULE_PATH

pushd submodule-repo
  commit_sha=`git rev-parse HEAD`
popd

pushd release-repo
  pushd ${SUBMODULE_PATH}
    git checkout $commit_sha
  popd

  git config --global alias.ci commit
  git config user.email "cf-diego-persistence@pivotal.io"
  git config user.name "persi-ci"
  git add ${SUBMODULE_PATH}
  set +e
    ./scripts/commit-with-submodule-logs
  set -e
popd

cp -a release-repo/. bumped-repo
