#!/bin/bash -e

collect_versions() {
  if [ ! -d ${ROOT_DIR}/diego-version ]; then
    echo "[ERROR] diego-version input is missing."
    exit 1
  fi
  if [ ! -d ${ROOT_DIR}/nfs-version ]; then
    echo "[ERROR] nfs-version input is missing."
    exit 1
  fi
  if [ ! -d ${ROOT_DIR}/efs-version ]; then
    echo "[ERROR] efs-version input is missing."
    exit 1
  fi
  if [ ! -d ${ROOT_DIR}/local-version ]; then
    echo "[ERROR] local-version input is missing."
    exit 1
  fi
  if [ ! -d ${ROOT_DIR}/csi-local-version ]; then
    echo "[ERROR] csi-local-version input is missing."
    exit 1
  fi
  if [ ! -d ${ROOT_DIR}/ecs-version ]; then
    echo "[ERROR] ecs-version input is missing."
    exit 1
  fi

  if [ ! -d ${ROOT_DIR}/cephfs-version ]; then
    echo "[ERROR] cephfs-version input is missing."
    exit 1
  fi


  DIEGO_VERSION="$(cat diego-version/number)"
  NFS_VERSION="$(cat nfs-version/number)"
  EFS_VERSION="$(cat efs-version/number)"
  LOCAL_VERSION="$(cat local-version/number)"
  CSI_LOCAL_VERSION="$(cat csi-local-version/number)"
  ECS_VERSION="$(cat ecs-version/number)"
  CEPHFS_VERSION="$(cat cephfs-version/number)"
}

check_params() {
  if [ ! -d ${ROOT_DIR}/diego-tarball ]; then
    echo "[ERROR] diego-tarball input is missing."
    exit 1
  fi
  if [ ! -d ${ROOT_DIR}/nfs-tarball ]; then
    echo "[ERROR] nfs-tarball input is missing."
    exit 1
  fi
  if [ ! -d ${ROOT_DIR}/efs-tarball ]; then
    echo "[ERROR] efs-tarball input is missing."
    exit 1
  fi
  if [ ! -d ${ROOT_DIR}/local-tarball ]; then
    echo "[ERROR] local-tarball input is missing."
    exit 1
  fi
  if [ ! -d ${ROOT_DIR}/csi-local-tarball ]; then
    echo "[ERROR] csi-local-tarball input is missing."
    exit 1
  fi
  if [ ! -d ${ROOT_DIR}/ecs-tarball ]; then
    echo "[ERROR] ecs-tarball input is missing."
    exit 1
  fi

  if [ ! -d ${ROOT_DIR}/cephfs-tarball ]; then
    echo "[ERROR] cephfs-tarball input is missing."
    exit 1
  fi

  if [ -z "${DIEGO_VERSION}" ]; then
    echo "[ERROR] DIEGO_VERSION is missing."
    exit 1
  fi
  if [ -z "${NFS_VERSION}" ]; then
    echo "[ERROR] NFS_VERSION is missing."
    exit 1
  fi
  if [ -z "${EFS_VERSION}" ]; then
    echo "[ERROR] EFS_VERSION is missing."
    exit 1
  fi
  if [ -z "${LOCAL_VERSION}" ]; then
    echo "[ERROR] LOCAL_VERSION is missing."
    exit 1
  fi
  if [ -z "${CSI_LOCAL_VERSION}" ]; then
    echo "[ERROR] CSI_LOCAL_VERSION is missing."
    exit 1
  fi
  if [ -z "${ECS_VERSION}" ]; then
    echo "[ERROR] ECS_VERSION is missing."
    exit 1
  fi
  if [ -z "${CEPHFS_VERSION}" ]; then
    echo "[ERROR] CEPHFS_VERSION is missing."
    exit 1
  fi

}

# Create collection directory (task output)
create_collection_directory() {
  mkdir -p ${ROOT_DIR}/collected-tarballs/operations
}

# Copy tarballs to collection with easy names
collect_tarballs() {
  cp ${ROOT_DIR}/diego-tarball/*.tgz ${ROOT_DIR}/collected-tarballs/diego.tgz
  cp ${ROOT_DIR}/nfs-tarball/*.tgz ${ROOT_DIR}/collected-tarballs/nfs.tgz
  cp ${ROOT_DIR}/efs-tarball/*.tgz ${ROOT_DIR}/collected-tarballs/efs.tgz
  cp ${ROOT_DIR}/csi-local-tarball/*.tgz ${ROOT_DIR}/collected-tarballs/csi-local.tgz
  cp ${ROOT_DIR}/ecs-tarball/*.tgz ${ROOT_DIR}/collected-tarballs/ecs.tgz
  cp ${ROOT_DIR}/local-tarball/*.tgz ${ROOT_DIR}/collected-tarballs/local.tgz
  cp ${ROOT_DIR}/cephfs-tarball/*.tgz ${ROOT_DIR}/collected-tarballs/cephfs.tgz
}

# Copy each new operation to collection
create_operation_file() {
    cat << EOF > ${ROOT_DIR}/collected-tarballs/operations/update-releases.yml
---
- type: replace
  path: /releases/name=diego
  value:
    name: diego
    version: ${DIEGO_VERSION}
    url: ops-files/diego.tgz
- type: replace
  path: /releases/name=nfs-volume
  value:
    name: nfs-volume
    version: ${NFS_VERSION}
    url: ops-files/nfs.tgz
- type: replace
  path: /releases/name=efs-volume
  value:
    name: efs-volume
    version: ${EFS_VERSION}
    url: ops-files/efs.tgz
- type: replace
  path: /releases/name=local-volume
  value:
    name: local-volume
    version: ${LOCAL_VERSION}
    url: ops-files/local.tgz
- type: replace
  path: /releases/name=csi-local-volume
  value:
    name: csi-local-volume
    version: ${CSI_LOCAL_VERSION}
    url: ops-files/csi-local.tgz
- type: replace
  path: /releases/name=ecs-release
  value:
    name: ecs-release
    version: ${ECS_VERSION}
    url: ops-files/ecs.tgz
- type: replace
  path: /releases/name=cephfs-release
  value:
    name: cephfs-release
    version: ${CEPHFS_VERSION}
    url: ops-files/cephfs.tgz
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties?/release_level_backup?
  value: false
- type: remove
  path: /instance_groups/name=backup-restore/jobs/name=bbr-uaadb
EOF
}

main() {
  ROOT_DIR="${1}"

  collect_versions
  check_params
  create_collection_directory
  collect_tarballs
  create_operation_file
}

main ${PWD}
