#!/bin/bash

set -x -e

version=`cat ecs-version/number`
tarball_name=efs-volume-$version.tgz
pushd ecs-release
    bosh -n create-release --version=$version --force --tarball $tarball_name
    mv $tarball_name ../created-ecs-release/
popd
