#!/bin/bash

set -x -e

version=`cat ecs-version/number`
pushd ecs-release

bosh -n --parallel 10 create release --version $version --name ecs-release --force --with-tarball
mv dev_releases/ecs-release/ecs-release-$version.tgz ../created-ecs-release/
popd
