#!/bin/bash

set -x -e

# TODO add versioning later
#version=`0-dev?`
pushd ecs-release

bosh -n --parallel 10 create release --name ecs-release --force --with-tarball
mv dev_releases/ecs-release/ecs-release*.tgz ../created-ecs-release/
popd
