#!/bin/bash

set -e -x -u

version=`cat version/number`

pushd diego-release
  bosh -n create-release --tarball=dev_releases/diego/diego-$version.tgz --version $version --force

  mv dev_releases/diego/*.tgz ../created-diego-release
popd
