#!/bin/bash -eu
set -ex

function finish {
  pkill ssh || true
}
trap finish EXIT

source persi-ci/scripts/ci/bbl_get_bosh_env
source bosh-env/set-env.sh

mkdir ops-files
cp ecs-release-tarball/*.tgz ops-files/ecs.tgz

bosh \
  -n \
  -d ecs \
  deploy vars-store/deployments/ecs/ecs.yml
