#!/bin/bash -eu
set -ex

function finish {
  pkill ssh || true
}
trap finish EXIT

source bosh-env/set-env.sh

mkdir ops-files
cp cephfs-bosh-release-tarball/*.tgz ops-files/cephfs.tgz

generate_cephfs_vars() {
    cat << EOF > ./cephfs-vars.yml
---
gorgophone-cephfs-keyring: |
`echo ${CEPHFS_KEYRING}|sed 's/^/  /'`
EOF
}

generate_cephfs_vars

bosh \
  -n \
  interpolate vars-store/manifest/cephfs.yml \
  --vars-file=./cephfs-vars.yml \
  > interpolated_manifest.yml

bosh \
  -n \
  -d cephfs \
  delete-deployment || true

bosh \
  -n \
  -d cephfs \
  deploy interpolated_manifest.yml
