#!/bin/bash -eux

if [ -d toolsmiths-env ]; then
  export ENV=`cat "toolsmiths-env/metadata" | jq -r ".name"`
  export SYSTEM_DOMAIN="${ENV}.cf-app.com"
fi

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

function main() {
  local root_dir
  root_dir="${PWD}"

  load_from_json_config

  check_input_params
  setup_bosh_env_vars
  cat <<EOF > ops-files/updated-releases.yml
---
- type: replace
  path: /releases/name=nfs-volume
  value:
    name: nfs-volume
    version: create
    url: file://${root_dir}/nfs-volume-release
- type: replace
  path: /releases/name=smb-volume
  value:
    name: smb-volume
    version: create
    url: file://${root_dir}/smb-volume-release
- type: replace
  path: /releases/name=mapfs
  value:
    name: mapfs
    version: create
    url: file://${root_dir}/mapfs-release
EOF

  export OPS_FILES="${OPS_FILES} updated-releases.yml"
  bosh_interpolate
  if [ "$REGENERATE_CREDENTIALS" == true ]; then
    remove_credentials_from_credhub
  fi
  upload_stemcells
  # shellcheck disable=SC2086
  bosh_deploy ${BOSH_DEPLOY_ARGS}
}

main
