#!/bin/bash -eu
set -ex

function finish {
  pkill ssh || true
}
trap finish EXIT

source bosh-env/set-env.sh

mkdir ops-files
cp ecs-release-tarball/*.tgz ops-files/ecs.tgz

bosh \
  -n \
  -d ecs \
  deploy vars-store/manifest/ecs.yml
