#!/bin/bash -eu

set -e -x

function finish {
  pkill ssh || true
}
trap finish EXIT

source persi-ci/scripts/ci/bbl_get_bosh_env
source bosh-env/set-env.sh

# install bosh
wget https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-2.0.28-linux-amd64
chmod +x bosh-cli-*
mv bosh-cli-* /usr/local/bin/bosh-cli

# install sshuttle
sudo apt-get -y install sshuttle

# export FOCUSED_SUITE_NAME="cf-nfsbroker|cf-smbbroker"
export FOCUSED_SUITE_NAME="cf-nfsbroker"
export CF_VARS_STORE_PATH="$PWD/vars-store/deployment-vars.yml"
export BBL_ENV="$PWD/director-state/$BBL_STATE_DIR"
export BBR_BUILD_PATH=$(pwd)/binary/bbr
export NFS_SERVICE_NAME
export NFS_PLAN_NAME
export NFS_BROKER_USER
export NFS_BROKER_PASSWORD
export NFS_BROKER_URL
export SMB_SERVICE_NAME
export SMB_PLAN_NAME
export SMB_BROKER_USER
export SMB_BROKER_PASSWORD
export SMB_BROKER_URL

# make a go project
mkdir -p runme
pushd runme/
    GOPATH=$PWD
    PATH=$GOPATH/bin:$PATH

    # install glide because drats doesn't
    mkdir -p $GOPATH/bin
    curl https://glide.sh/get | sh

    go get -u github.com/golang/dep/cmd/dep

    mkdir -p src/github.com/cloudfoundry-incubator/
    pushd src/github.com/cloudfoundry-incubator/
#        git clone https://github.com/julian-hj/disaster-recovery-acceptance-tests.git
        git clone https://github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests.git

        # run drats
        pushd disaster-recovery-acceptance-tests/
            scripts/run_acceptance_tests_with_bbl_env.sh $BBL_ENV
        popd
    popd
popd
