#!/bin/bash

set -e -x -u

source persi-ci/scripts/ci/utils.sh

check_param BASE_RELEASE_NAME
check_param GIT_USER
check_param GIT_EMAIL
check_param S3_ACCESS_KEY_ID
check_param S3_ACCESS_KEY

RELEASE=release
TARBALL=release-tarball
VERSION=version

echo "----- Copy private blobstore credentials into release"
cat > "${RELEASE}/config/private.yml" <<EOF
---
blobstore:
  options:
    access_key_id: ${S3_ACCESS_KEY_ID}
    secret_access_key: ${S3_ACCESS_KEY}
EOF

FINAL_RELEASE_VERSION="$(cat "${VERSION}/number")"
DEV_RELEASE_TARBALL="$(ls "${PWD}/${TARBALL}"/*.tgz)"

pushd "${RELEASE}"
  RELEASE_YML="${PWD}/releases/${BASE_RELEASE_NAME}/${BASE_RELEASE_NAME}-${FINAL_RELEASE_VERSION}.yml"

  git pull

  # idempotently create tarball in case later parts of shipit fail
  if [[ ! -e "${RELEASE_YML}" ]]; then
    echo "----- Set git identity"
    git config user.email "${GIT_EMAIL}"
    git config user.name "${GIT_USER}"

    echo "----- Create final release"
    bosh -n finalize-release "${DEV_RELEASE_TARBALL}" --version="${FINAL_RELEASE_VERSION}"

    echo "----- Update master and develop branches on origin"
    git add -A
    git commit -m "Create final release ${FINAL_RELEASE_VERSION} [ci skip]"

    echo "----- DEBUG: show the commit we just created"
    git --no-pager show HEAD
  fi
popd

cp -a "${RELEASE}" finalized-release/
