#!/bin/bash -e

generate_nfs_vars() {
    cat << EOF > ${ROOT_DIR}/generated-vars/nfs-vars.yml
---
nfs-ldap-service-user: ${LDAP_SVC_USER}
nfs-ldap-service-password: ${LDAP_SVC_PASS}
nfs-ldap-host: ${LDAP_HOST}
nfs-ldap-port: ${LDAP_PORT}
nfs-ldap-proto: ${LDAP_PROTO}
nfs-ldap-fqdn: ${LDAP_USER_FQDN}
EOF
}

generate_efs_vars() {
    cat << EOF > ${ROOT_DIR}/generated-vars/efs-vars.yml
---
aws-access-key-id: ${AWS_ACCESS_KEY_ID}
aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
aws-subnet-id: ${AWS_SUBNET_ID}
aws-security-group: ${AWS_SECURITY_GROUP}
efs-broker-password: ${EFS_BROKER_PASSWORD}
EOF
}

generate_cf_vars() {
    cat << EOF > ${ROOT_DIR}/generated-vars/cf-vars.yml
---
ecs-password: ${ECS_PASSWORD}
ecs-username: ${ECS_USERNAME}
ecs-ip: ${ECS_IP}
ecs-aws-id: ${ECS_AWS_ID}
ecs-aws-key: ${ECS_AWS_KEY}

blobstore_access_key_id: ${S3_BLOBSTORE_ID}
blobstore_secret_access_key: ${S3_BLOBSTORE_KEY}
aws_region: ${S3_BLOBSTORE_REGION}

app_package_directory_key: ${APP_PACKAGE_DIRECTORY_KEY}
buildpack_directory_key: ${BUILDPACK_DIRECTORY_KEY}
droplet_directory_key: ${DROPLET_DIRECTORY_KEY}
resource_directory_key: ${RESOURCE_DIRECTORY_KEY}
EOF
}

generate_datadog_vars() {
    cat << EOF > ${ROOT_DIR}/generated-vars/datadog-vars.yml
---
datadog_api_key: ${DATADOG_API_KEY}
datadog_metric_prefix: ${DATADOG_METRIC_PREFIX}
traffic_controller_external_port: 4443
EOF
}

generate_cephfs_vars() {
    cat << EOF > ${ROOT_DIR}/generated-vars/cephfs-vars.yml
---
gorgophone-cephfs-keyring: ${CEPHFS_KEYRING}
EOF
}



main() {
  ROOT_DIR="${1}"
  mkdir -p ${ROOT_DIR}/generated-vars

  generate_nfs_vars
  generate_efs_vars
  generate_cf_vars
  generate_datadog_vars
  generate_cephfs_vars
}

main ${PWD}
