platform: linux
image_resource:
  type: docker-image
  source:
    repository: cryogenics/essentials
    tag: 0.1.51
inputs:
  - name: smith-env
    optional: true
  - name: persi-ci
outputs:
  - name: pats-config
params:
  VAR_RESOLVER_SCRIPT: persi-ci/scripts/ci/pas_helpers.sh
  CF_USERNAME: admin
  BIND_BOGUS_CONFIG:
  BIND_CONFIG:
  BROKER_URL:
  BROKER_USER:
  BROKER_PASSWORD:
  CREATE_BOGUS_CONFIG:
  CREATE_CONFIG:
  DEFAULT_TIMEOUT: 30
  DISALLOWED_LDAP_BIND_CONFIG:
  DISALLOWED_OVERRIDE_BIND_CONFIG:
  PLAN_NAME:
  SERVICE_NAME:
  TOOLSMITHS_API_TOKEN:
run:
  path: persi-ci/scripts/ci/generate_pats_config.sh
