#!/bin/bash -ex

mkdir -p generated-efs-tile-product-config
OUTPUT_DIR="$PWD/generated-efs-tile-product-config"

pushd bbl-state/${BBL_ENV}

  AWS_REGION=$(bbl outputs | yq -r .region)
  AWS_SUBNETS=$(bbl outputs | yq -r .internal_az_subnet_id_mapping.\"`bbl outputs | yq -r .az`\")
  AWS_SECURITY_GROUP_IDS=$(bbl outputs | yq -r .internal_security_group)
  AWS_AZS=$(bbl outputs | yq -r .az)
  NETWORK_PROPERTIES=$(cat ../pcf/metadata | jq -r .service_subnet_name)
  OTHER_AVAILABILITY_ZONES=$(cat ../pcf/metadata | jq -cr '.azs | map( {name: .} )')
  SINGLETON_AVAILABILITY_ZONE=$(cat ../pcf/metadata | jq -r '.azs | map( {name: .} )[0].name')

  cat <<EOF >${OUTPUT_DIR}/generated-efs-tile-product-config.yml
---
product-name: aws-efs-broker
product-properties:
  .properties.aws_access_key_id:
    value: "${AWS_ACCESS_KEY_ID}"
  .properties.aws_secret_access_key:
    value:
      secret: "${AWS_SECRET_ACCESS_KEY}"
  .properties.aws_region:
    value: "${AWS_REGION}"
  .properties.aws_subnet_ids:
    value: "${AWS_SUBNETS}"
  .properties.aws_security_group_ids:
    value: "${AWS_SECURITY_GROUP_IDS}"
  .properties.aws_azs:
    value: "${AWS_AZS}"
network-properties:
  network:
    name: ${NETWORK_PROPERTIES}
  other_availability_zones: ${OTHER_AVAILABILITY_ZONES}
  singleton_availability_zone:
    name: ${SINGLETON_AVAILABILITY_ZONE}
resource-config:
  efsbroker:
    instances: automatic
EOF

popd
