#!/bin/sh

set -e -x -u
source $(pwd)/persi-ci/scripts/ci/utils.sh
check_param BASE_RELEASE_NAME

version=$(cat version/number)

( cd release && git rev-parse HEAD ) > generated-release/commitish
echo "${BASE_RELEASE_NAME} v$version" > generated-release/name
echo "v$version" > generated-release/version
