#!/bin/sh

set -e -x -u
source $(pwd)/persi-ci/scripts/ci/utils.sh
check_param RELEASE
check_param BASE_RELEASE_NAME


( cd ${RELEASE} && git rev-parse HEAD ) > generated-release/commitish

version=$(cat ${VERSION}/number)
echo "${BASE_RELEASE_NAME} v$version" > generated-release/name
echo "v$version" > generated-release/version