#!/usr/bin/env bash

set -x -e

cp -r base-ops-files/* collected-ops-files/

bosh int cf-deployment/cf-deployment.yml --path /instance_groups/name=diego-cell > diego-cell-dup.yml

bosh int base-ops-files/operations/add-diego-cell-ldap.yml -l diego-cell-dup.yml > collected-ops-files/operations/add-diego-cell-ldap.yml
