#!/bin/bash -e

generate_nfs_vars() {
    cat << EOF > ${ROOT_DIR}/generated-vars/nfs-vars.yml
---
nfs-ldap-service-user: ${LDAP_SVC_USER}
nfs-ldap-service-password: ${LDAP_SVC_PASS}
nfs-ldap-host: ${LDAP_HOST}
nfs-ldap-port: ${LDAP_PORT}
nfs-ldap-proto: ${LDAP_PROTO}
nfs-ldap-fqdn: ${LDAP_USER_FQDN}

ecs-password: ${ECS_PASSWORD}
ecs-username: ${ECS_USERNAME}
ecs-ip: ${ECS_IP}
ecs-aws-id: ${ECS_AWS_ID}
ecs-aws-key: ${ECS_AWS_KEY}
EOF
}

generate_cf_vars() {
    cat << EOF > ${ROOT_DIR}/generated-vars/cf-vars.yml
---
app_package_directory_key: ${APP_PACKAGE_DIRECTORY_KEY}
buildpack_directory_key: ${BUILDPACK_DIRECTORY_KEY}
droplet_directory_key: ${DROPLET_DIRECTORY_KEY}
resource_directory_key: ${resource_directory_key}
EOF
}


main() {
  ROOT_DIR="${1}"
  mkdir -p ${ROOT_DIR}/generated-vars

  generate_nfs_vars
  generate_cf_vars
}

main ${PWD}
