#!/bin/bash -e

generate_nfs_vars() {
    mkdir -p ${ROOT_DIR}/generated-vars

    cat << EOF > ${ROOT_DIR}/generated-vars/nfs-vars.yml
---
- nfs-ldap-svc-user: ${LDAP_SVC_USER}
- nfs-ldap-svc-password: ${LDAP_SVC_PASS}
- nfs-ldap-host: ${LDAP_HOST}
- nfs-ldap-port: ${LDAP_PORT}
- nfs-ldap-proto: ${LDAP_PROTO}
- nfs-ldap-user-fqdn: ${LDAP_USER_FQDN}
EOF
}

main() {
  ROOT_DIR="${1}"

  generate_nfs_vars
}

main ${PWD}