#!/usr/bin/env bash

set -x -e

cp -r base-ops-files/* collected-ops-files/

bosh int cf-deployment/cf-deployment.yml --path /instance_groups/name=diego-cell > diego-cell-dup.yml

bosh int base-ops-files/add-diego-cell-tagged.yml -l diego-cell-dup.yml > collected-ops-files/parsed-diego-cell-tagged.yml
