#!/bin/bash -eu

set -e -x

source bosh-env/set-env.sh


export CF_PASSWORD=`cat vars-store/deployment-vars.yml | grep cf_admin_password|awk '{print $2}'`
export ASSETS_PATH=${PWD}/assets/builds/lib/spring-music.jar

cf api api.${DOMAIN_NAME} --skip-ssl-validation

mkdir -p runme/src/code.cloudfoundry.org
cp -rf persistence-load-tests runme/src/code.cloudfoundry.org/

pushd runme
    GOPATH=$PWD
    PATH=$GOPATH/bin:$PATH
    cd src/code.cloudfoundry.org/persistence-load-tests
    go get ./...

    ginkgo -r
popd

