---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cryogenics/essentials
    tag: latest

inputs:
- name: persi-ci
- name: toolsmiths-env  # - Directory containing Toolsmiths metadata file
- name: cf-deployment  # - The cf-deployment manifest

outputs:
- name: cf-deployment-pinned

run:
  path: persi-ci/scripts/ci/pin_cf_deployment_version
