#!/bin/bash -eux

if [ -d toolsmiths-env ]; then
  VERS=$(jq -r '."cf-deployment_version"' toolsmiths-env/metadata)

  cp -a cf-deployment/. cf-deployment-pinned/

  pushd cf-deployment-pinned
    git fetch --tags
    git checkout "v${VERS}"
  popd
fi
