#!/bin/bash -eux

if [ -d toolsmiths-env ]; then
  VERS=$(jq -r '."cf-deployment_version"' toolsmiths-env/metadata)
  if [[ "$VERS" =~ ^[0-9] ]]; then
    VERS="v${VERS}"
  fi

  cp -a cf-deployment/. cf-deployment-pinned/

  pushd cf-deployment-pinned
    git fetch --tags
    git checkout $VERS
  popd
fi
