#!/bin/bash
set -ex

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH
export GOPATH=$PWD
export PATH=$PWD/bin:$PATH

if ! ginkgo version &> /dev/null
then
  go get -u github.com/onsi/ginkgo/ginkgo
fi

cd gomod
export GO111MODULE=on
ginkgo -r -keepGoing -p -race -trace -randomizeAllSpecs -progress -mod=vendor -nodes $NODES
