#!/bin/bash

set -e -x

cd diego-release/

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

export GOPATH=$PWD
export PATH=$PWD/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

pushd src/code.cloudfoundry.org/volman
  ginkgo -r -keepGoing -p -trace -randomizeAllSpecs -progress --race "$@"
popd

pushd src/code.cloudfoundry.org/dockerdriver
  ginkgo -r -keepGoing -p -trace -randomizeAllSpecs -progress --race "$@"
popd
