#!/bin/bash
# vim: set ft=sh

set -e -x

scripts_path=./$(dirname $0)/..
eval $($scripts_path/get_paths.sh)

if [ "$(uname)" == "Darwin" ]; then
    export GOPATH=`greadlink -f ${scripts_path}/..`
else
    export GOPATH=`readlink -f ${scripts_path}/..`
fi
export PATH=$GOPATH/bin:$PATH

source ${scripts_path}/ci/utils.sh
check_param CF_USERNAME
check_param CF_PASSWORD
check_param CF_API_ENDPOINT
check_param APPS_DOMAIN
check_param SERVICE_NAME
check_param PLAN_NAME
check_param BROKER_URL
check_param BROKER_USER
check_param BROKER_PASSWORD
check_param SERVER_ADDRESS
check_param SHARE
check_param BIND_CONFIG
check_param TEST_MULTI_CELL
check_param TEST_MOUNT_OPTIONS
check_param TEST_READ_ONLY

if [ -z "$APPLICATION_PATH" ]; then
    export APPLICATION_PATH=${GOPATH}/src/code.cloudfoundryorg/persi-acceptance-tests/assets/pora
fi

go get github.com/onsi/ginkgo/ginkgo
go get github.com/cloudfoundry-incubator/cf-test-helpers/cf
go get github.com/cloudfoundry-incubator/cf-test-helpers/helpers
go get -d code.cloudfoundry.org/persi-acceptance-tests

${scripts_path}/ci/run_pats \
${CF_USERNAME} \
${CF_PASSWORD} \
${CF_API_ENDPOINT} \
${APPS_DOMAIN} \
${SERVICE_NAME} \
${PLAN_NAME} \
${BROKER_URL} \
${BROKER_USER} \
${BROKER_PASSWORD} \
${SERVER_ADDRESS} \
${SHARE} \
${BIND_CONFIG} \
${PUSHED_BROKER_NAME} \
${DB_SERVICE_INSTANCE_NAME}