#!/bin/bash
set -eux

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

pushd release-dir
    if [[ ! -z "${RELEASE_DIR}" ]]; then
        export GOPATH=$PWD
        export PATH=$PWD/bin:$PATH
    fi

    go get github.com/securego/gosec/cmd/gosec

    IFS=':' read -r -a array <<< "$PATHS"

    for path in "${array[@]}"; do
      pushd $path
        GO111MODULE=auto gosec "./..."
      popd
    done

popd
