#!/bin/bash

set -eu pipefail

persi-ci/scripts/ci/bbl_get_bosh_env
source bosh-env/set-env.sh

pushd director-state/$BBL_STATE_DIR/
    NS0=$(bbl outputs | yq -r '.system_domain_dns_servers[0]')
    NS1=$(bbl outputs | yq -r '.system_domain_dns_servers[1]')
    NS2=$(bbl outputs | yq -r '.system_domain_dns_servers[2]')
    NS3=$(bbl outputs | yq -r '.system_domain_dns_servers[3]')
popd

cat << EOF > file.txt
{
  "Comment": "bbl up CI task updating the persi ephemeral name servers",
  "Changes": [
    {
      "Action": "UPSERT",
      "ResourceRecordSet": {
        "Name": "${NS_RECORD_NAME}",
        "Type": "NS",
        "TTL": 0,
        "ResourceRecords": [
          {"Value": "$NS0"},
          {"Value": "$NS1"},
          {"Value": "$NS2"},
          {"Value": "$NS3"}
        ]
      }
    }
  ]
}
EOF

aws route53 change-resource-record-sets \
  --hosted-zone-id /hostedzone/$AWS_HOSTED_ZONE \
  --change-batch "$(cat ./file.txt)"

