#!/bin/bash
set -u

NFS_LTS_VERSION="$1"
fly -t persi sp \
  -p "lts-${NFS_LTS_VERSION}" \
  -c lts.yml \
  --load-vars-from <( lpass show pipeline-secrets --notes ) \
  -v lts-nfs-branch="v${NFS_LTS_VERSION}" \
  -v nfs-semver-initial-version=2.3.3 \
  -v mapfs-tag=v1.2.0 \
  -v cf-d-version-tag=v12.1.0 \
  -v cf-d-tasks-version-tag=v10.9.0
