#!/bin/bash
set -u

# Usage
# ./scripts/fly-lts-toolsmiths 5.0
# ./scripts/fly-lts-toolsmiths 2.3

NFS_LTS_VERSION="$1"
MAPFS_VERSION_TAG="v1.2.0"

if [[ "${NFS_LTS_VERSION}" = "2.3" ]]; then
  PAS_VERSION="us_2_7"
  NFS_LTS_INITIAL_VERSION="2.3.3"
else
  PAS_VERSION="us_2_8"
  NFS_LTS_INITIAL_VERSION="5.0.3"
fi

fly -t persi sp \
  -p "lts-toolsmiths-${NFS_LTS_VERSION}" \
  -c "lts-toolsmiths.yml" \
  --load-vars-from <( lpass show pipeline-secrets --notes ) \
  -v lts-nfs-branch="v${NFS_LTS_VERSION}" \
  -v nfs-semver-initial-version="${NFS_LTS_INITIAL_VERSION}" \
  -v mapfs-tag="${MAPFS_VERSION_TAG}" \
  -v pas-version="${PAS_VERSION}"