#!/bin/bash
set -u

# Usage
# ./scripts/fly-lts

NFS_LTS_VERSION="1.7"
PIPELINE_NAME="lts.yml"

CF_D_VERSION_TAG="v7.5.0"
NFS_LTS_INITIAL_VERSION="1.7.13"
MAPFS_VERSION_TAG="v1.2.0"
PIPELINE_NAME="lts-1-7.yml"

fly -t persi sp \
  -p "lts-${NFS_LTS_VERSION}" \
  -c $PIPELINE_NAME \
  --load-vars-from <( lpass show pipeline-secrets --notes ) \
  -v lts-nfs-branch="v${NFS_LTS_VERSION}" \
  -v nfs-semver-initial-version="${NFS_LTS_INITIAL_VERSION}" \
  -v mapfs-tag="${MAPFS_VERSION_TAG}" \
  -v cf-d-version-tag="${CF_D_VERSION_TAG}" \
  -v nfs-volume-release-tarball-regexp="nfs-volume-(${NFS_LTS_VERSION}.*).tgz" \
  -v cf-d-tasks-version-tag=v10.9.0
