#!/bin/bash -eu

function main() {
  local cwd="${1}"

  local tmpdir
  tmpdir="$(mktemp -d)"

  authenticate

  pushd "${tmpdir}" > /dev/null
    local pipes
    pipes=($(fly -t persi pipelines | grep -v "^==" | cut -d' ' -f1))

    for pipeline in "${pipes[@]}"; do
      echo "Fetching pipeline: ${pipeline}"
      fly -t persi gp -p "${pipeline}" > "${pipeline}".yml
    done
  popd > /dev/null

  local pipelines
  pipelines=($(find "${tmpdir}" -name "*.yml"))

  local pipeline_tasks
  pipeline_tasks=($(
    for pipeline in "${pipelines[@]}"; do
      egrep "\bfile:" "${pipeline}" | sed -e "s/^[ \t]*//" | sed -e "s/*[ \t]$//" | egrep ".*\.yml$" | sed -e "s/^file: persi-ci\/*//"
    done | sort -d | uniq
  ))

  local tasks
  tasks=($(
    cat <(find "${cwd}/scripts/ci" -name "*.yml" | grep -v "fixtures") | while read -r t; do
      local path
      path="${t#${cwd}/}"

      if ag "^platform:" "${path}" > /dev/null; then
        echo "${path}"
      fi
    done | sort -d | uniq
  ))

  local unused_tasks
  unused_tasks=($(
    for t in "${tasks[@]}"; do
      if [[ $(contains "${pipeline_tasks[@]}" "${t}") == "n" ]]; then
        echo "${t}"
      fi
    done
  ))

  if (( "${#unused_tasks[@]}" != 0 )); then
    echo "The following tasks could not be detected in CI:"
    for t in "${unused_tasks[@]}"; do
      echo "  ${t}"
    done
  else
    echo "Congrats! No unused tasks."
  fi

  for pipeline in "${pipelines[@]}"; do
    rm "${pipeline}"
  done

  rmdir "${tmpdir}"
}

function contains() {
  local n="$#"
  local value="${!n}"
  for ((i=1; i < "$#"; i++)) {
    if [ "${!i}" == "${value}" ]; then
      echo "y"
      return 0
    fi
  }

  echo "n"
  return 1
}

function authenticate() {
  if [[ -n "$(fly -t persi pipelines | head -n1 | xargs -I {} fly -t persi checklist -p {} 2>&1 | grep -E "not authorized|forbidden")" ]]; then
    fly -t persi login
  fi
}

main "$(cd "$(dirname "${0}")" && cd .. && pwd)"
