#!/bin/bash
set -eux

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

source cf-deployment-concourse-tasks/cf-deployment-concourse-tasks/bosh-upload-stemcell-from-cf-deployment/task

source deployments-persi/persi-ci/deployments/bosh-lite-aws/setenv.sh

function main() {
  check_upload_stemcell_params
#  setup_bosh_env_vars 'bbl-state'
  upload_stemcell
}

main